import { describe, it, expect, beforeEach } from 'vitest'
import { RecoveryKeyService } from '../RecoveryKeyService'

function freshInstance(): RecoveryKeyService {
  // Access the singleton and reset it so each test starts clean
  const instance = RecoveryKeyService.getInstance()
  instance.clear()
  return instance
}

describe('RecoveryKeyService', () => {
  let service: RecoveryKeyService

  beforeEach(() => {
    service = freshInstance()
  })

  // ─── Mnemonic generation ───────────────────────────────────

  describe('generateMnemonic', () => {
    it('generates 12 words by default', async () => {
      const words = await service.generateMnemonic()
      expect(words).toHaveLength(12)
    })

    it('generates 24 words when requested', async () => {
      const words = await service.generateMnemonic(24)
      expect(words).toHaveLength(24)
    })

    it('produces different mnemonics on each call', async () => {
      const a = await service.generateMnemonic()
      const b = await service.generateMnemonic()
      expect(a.join(' ')).not.toBe(b.join(' '))
    })

    it('only contains words from the wordlist', async () => {
      const words = await service.generateMnemonic()
      for (const word of words) {
        expect(service.validateMnemonic([
          word, 'abandon', 'ability', 'able', 'about', 'above',
          'absent', 'absorb', 'abstract', 'absurd', 'abuse', 'access'
        ])).toBe(true)
      }
    })

    it('passes strict BIP39 checksum validation', async () => {
      const words = await service.generateMnemonic(12)
      expect(await service.validateMnemonicStrict(words)).toBe(true)
    })

    it('passes strict BIP39 checksum validation for 24-word phrases', async () => {
      const words = await service.generateMnemonic(24)
      expect(await service.validateMnemonicStrict(words)).toBe(true)
    })
  })

  // ─── Mnemonic validation ───────────────────────────────────

  describe('validateMnemonic', () => {
    it('accepts valid 12-word mnemonics', async () => {
      const words = await service.generateMnemonic(12)
      expect(service.validateMnemonic(words)).toBe(true)
    })

    it('accepts valid 24-word mnemonics', async () => {
      const words = await service.generateMnemonic(24)
      expect(service.validateMnemonic(words)).toBe(true)
    })

    it('rejects wrong word count', () => {
      expect(service.validateMnemonic(['abandon', 'ability'])).toBe(false)
    })

    it('rejects words not in wordlist', () => {
      const words = Array(12).fill('notarealword')
      expect(service.validateMnemonic(words)).toBe(false)
    })
  })

  describe('validateMnemonicStrict (BIP39 checksum)', () => {
    it('rejects phrases generated by the legacy (non-checksum) generator', async () => {
      const legacy = service.generateMnemonicSync(12)
      // Strict validation should usually fail because the legacy generator
      // uses a pseudo-checksum (first 4 bits of entropy[0]) rather than the
      // SHA-256 checksum. Run a few attempts to avoid flakiness from a
      // chance collision.
      let strictRejected = 0
      for (let i = 0; i < 8; i++) {
        const w = service.generateMnemonicSync(12)
        if (!(await service.validateMnemonicStrict(w))) strictRejected++
      }
      // At least one should fail strict validation; the legacy checksum
      // can occasionally collide with the real SHA-256 checksum (≈1/16).
      expect(strictRejected).toBeGreaterThan(0)
      expect(legacy).toHaveLength(12)
    })

    it('rejects tampered phrases', async () => {
      const words = await service.generateMnemonic(12)
      // The original phrase must validate.
      expect(await service.validateMnemonicStrict(words)).toBe(true)

      // Tampering the last word is unreliable on its own: word 12 carries the
      // 4 checksum bits, so for any 11-word prefix roughly 1/16 of the 2048
      // wordlist entries still produce a valid checksum. Instead, try tampering
      // multiple words and require that at least one tampering is rejected.
      // (In practice virtually all of them will be.)
      let rejected = 0
      for (let pos = 0; pos < 12; pos++) {
        const tampered = [...words]
        tampered[pos] = tampered[pos] === 'abandon' ? 'ability' : 'abandon'
        if (tampered[pos] === words[pos]) continue
        if (!(await service.validateMnemonicStrict(tampered))) rejected++
      }
      expect(rejected).toBeGreaterThan(0)
    })
  })

  // ─── Mnemonic parsing ─────────────────────────────────────

  describe('parseMnemonicInput', () => {
    it('splits whitespace-separated input', () => {
      const result = service.parseMnemonicInput('abandon ability able about above absent absorb abstract absurd abuse access accident')
      expect(result).toHaveLength(12)
      expect(result[0]).toBe('abandon')
    })

    it('lowercases input', () => {
      const result = service.parseMnemonicInput('ABANDON ABILITY')
      expect(result).toEqual(['abandon', 'ability'])
    })

    it('strips non-letter characters', () => {
      const result = service.parseMnemonicInput('1. abandon 2. ability')
      expect(result).toEqual(['abandon', 'ability'])
    })
  })

  // ─── Key derivation (real PBKDF2 + HKDF) ─────────────────

  describe('deriveKeysFromMnemonic', () => {
    const TEST_MNEMONIC = [
      'abandon', 'ability', 'able', 'about', 'above', 'absent',
      'absorb', 'abstract', 'absurd', 'abuse', 'access', 'accident'
    ]

    it('derives three distinct keys', async () => {
      const keys = await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      expect(keys.encryptionKey).toBeDefined()
      expect(keys.backupKey).toBeDefined()
      expect(keys.signingKey).toBeDefined()
    })

    it('encryption key is AES-GCM 256-bit', async () => {
      const keys = await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      const exported = await crypto.subtle.exportKey('raw', keys.encryptionKey)
      expect(exported.byteLength).toBe(32)
    })

    it('backup key is AES-GCM 256-bit', async () => {
      const keys = await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      const exported = await crypto.subtle.exportKey('raw', keys.backupKey)
      expect(exported.byteLength).toBe(32)
    })

    it('encryption and backup keys are different', async () => {
      const keys = await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      const encRaw = new Uint8Array(await crypto.subtle.exportKey('raw', keys.encryptionKey))
      const bkpRaw = new Uint8Array(await crypto.subtle.exportKey('raw', keys.backupKey))
      expect(encRaw).not.toEqual(bkpRaw)
    })

    it('is deterministic - same mnemonic yields same keys', async () => {
      const keys1 = await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      const raw1 = new Uint8Array(await crypto.subtle.exportKey('raw', keys1.encryptionKey))

      service.clear()
      const keys2 = await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      const raw2 = new Uint8Array(await crypto.subtle.exportKey('raw', keys2.encryptionKey))

      expect(raw1).toEqual(raw2)
    })

    it('different mnemonics yield different keys', async () => {
      const keys1 = await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      const raw1 = new Uint8Array(await crypto.subtle.exportKey('raw', keys1.encryptionKey))

      service.clear()
      const altMnemonic = [
        'zoo', 'zoo', 'zoo', 'zoo', 'zoo', 'zoo',
        'zoo', 'zoo', 'zoo', 'zoo', 'zoo', 'wrong'
      ]
      const keys2 = await service.deriveKeysFromMnemonic(altMnemonic)
      const raw2 = new Uint8Array(await crypto.subtle.exportKey('raw', keys2.encryptionKey))

      expect(raw1).not.toEqual(raw2)
    })

    it('rejects invalid mnemonic', async () => {
      await expect(
        service.deriveKeysFromMnemonic(['not', 'a', 'valid', 'mnemonic'])
      ).rejects.toThrow('Invalid mnemonic')
    })
  })

  // ─── Backup encrypt / decrypt round-trip (real AES-GCM) ───

  describe('encryptForBackup / decryptFromBackup', () => {
    const TEST_MNEMONIC = [
      'abandon', 'ability', 'able', 'about', 'above', 'absent',
      'absorb', 'abstract', 'absurd', 'abuse', 'access', 'accident'
    ]

    beforeEach(async () => {
      await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
    })

    it('round-trips plaintext through encrypt → decrypt', async () => {
      const plaintext = 'Hello, encrypted world!'
      const encrypted = await service.encryptForBackup(plaintext)
      const decrypted = await service.decryptFromBackup(encrypted)
      expect(decrypted).toBe(plaintext)
    })

    it('round-trips JSON data', async () => {
      const data = JSON.stringify({ sessions: [{ id: 'abc', key: 'xyz' }] })
      const encrypted = await service.encryptForBackup(data)
      const decrypted = await service.decryptFromBackup(encrypted)
      expect(JSON.parse(decrypted)).toEqual(JSON.parse(data))
    })

    it('produces different ciphertext each time (random IV)', async () => {
      const plaintext = 'same data'
      const a = await service.encryptForBackup(plaintext)
      const b = await service.encryptForBackup(plaintext)
      expect(a).not.toBe(b)
    })

    it('fails to decrypt with wrong key', async () => {
      const plaintext = 'secret data'
      const encrypted = await service.encryptForBackup(plaintext)

      // Re-derive with a different mnemonic
      service.clear()
      await service.deriveKeysFromMnemonic([
        'zoo', 'zoo', 'zoo', 'zoo', 'zoo', 'zoo',
        'zoo', 'zoo', 'zoo', 'zoo', 'zoo', 'wrong'
      ])

      await expect(service.decryptFromBackup(encrypted)).rejects.toThrow()
    })

    it('throws if keys not loaded', async () => {
      service.clear()
      await expect(service.encryptForBackup('test')).rejects.toThrow('Recovery key not loaded')
      await expect(service.decryptFromBackup('dGVzdA==')).rejects.toThrow('Recovery key not loaded')
    })
  })

  // ─── Verification code ────────────────────────────────────

  describe('verification code', () => {
    const TEST_MNEMONIC = [
      'abandon', 'ability', 'able', 'about', 'above', 'absent',
      'absorb', 'abstract', 'absurd', 'abuse', 'access', 'accident'
    ]

    it('generates a 6-character hex code', async () => {
      await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      const code = await service.generateVerificationCode()
      expect(code).toMatch(/^[0-9A-F]{6}$/)
    })

    it('is deterministic for same mnemonic', async () => {
      await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      const code1 = await service.generateVerificationCode()

      service.clear()
      await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      const code2 = await service.generateVerificationCode()

      expect(code1).toBe(code2)
    })

    it('verifies correct recovery phrase', async () => {
      await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      const code = await service.generateVerificationCode()
      const verified = await service.verifyRecoveryPhrase(TEST_MNEMONIC, code)
      expect(verified).toBe(true)
    })

    it('rejects wrong recovery phrase', async () => {
      await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      const code = await service.generateVerificationCode()
      const wrongPhrase = [
        'zoo', 'zoo', 'zoo', 'zoo', 'zoo', 'zoo',
        'zoo', 'zoo', 'zoo', 'zoo', 'zoo', 'wrong'
      ]
      const verified = await service.verifyRecoveryPhrase(wrongPhrase, code)
      expect(verified).toBe(false)
    })
  })

  // ─── QR code data ─────────────────────────────────────────

  describe('QR code support', () => {
    const TEST_MNEMONIC = [
      'abandon', 'ability', 'able', 'about', 'above', 'absent',
      'absorb', 'abstract', 'absurd', 'abuse', 'access', 'accident'
    ]

    it('returns null when no mnemonic loaded', () => {
      expect(service.generateQRData()).toBeNull()
    })

    it('round-trips mnemonic through QR data', async () => {
      await service.deriveKeysFromMnemonic(TEST_MNEMONIC)
      const qrData = service.generateQRData()
      expect(qrData).toBeTruthy()

      const parsed = service.parseQRData(qrData!)
      expect(parsed).toEqual(TEST_MNEMONIC)
    })
  })

  // ─── State management ─────────────────────────────────────

  describe('state management', () => {
    it('reports not loaded initially', () => {
      expect(service.isLoaded()).toBe(false)
      expect(service.getEncryptionKey()).toBeNull()
      expect(service.getBackupKey()).toBeNull()
    })

    it('reports loaded after key derivation', async () => {
      await service.deriveKeysFromMnemonic([
        'abandon', 'ability', 'able', 'about', 'above', 'absent',
        'absorb', 'abstract', 'absurd', 'abuse', 'access', 'accident'
      ])
      expect(service.isLoaded()).toBe(true)
      expect(service.getEncryptionKey()).not.toBeNull()
      expect(service.getBackupKey()).not.toBeNull()
    })

    it('clears state on clear()', async () => {
      await service.deriveKeysFromMnemonic([
        'abandon', 'ability', 'able', 'about', 'above', 'absent',
        'absorb', 'abstract', 'absurd', 'abuse', 'access', 'accident'
      ])
      service.clear()
      expect(service.isLoaded()).toBe(false)
      expect(service.getEncryptionKey()).toBeNull()
    })
  })
})
