/**
 * Playwright fixtures for authenticated test users.
 *
 * Provides pre-authenticated Page instances (alicePage, bobPage) using
 * storageState files generated by global-setup.ts.
 *
 * Also exposes seedData for accessing server/channel/user IDs in tests.
 */

import { test as base, type Page } from '@playwright/test'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import type { SeedData } from '../global-setup'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const AUTH_DIR = path.resolve(__dirname, '../.auth')

type AuthFixtures = {
  alicePage: Page
  bobPage: Page
  seedData: SeedData
}

export const test = base.extend<AuthFixtures>({
  alicePage: async ({ browser }, use) => {
    const ctx = await browser.newContext({
      storageState: path.resolve(AUTH_DIR, 'alice.json'),
    })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  bobPage: async ({ browser }, use) => {
    const ctx = await browser.newContext({
      storageState: path.resolve(AUTH_DIR, 'bob.json'),
    })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  seedData: async ({}, use) => {
    const seedPath = path.resolve(AUTH_DIR, 'seed-data.json')
    const data: SeedData = JSON.parse(fs.readFileSync(seedPath, 'utf-8'))
    await use(data)
  },
})

export { expect } from '@playwright/test'
