/**
 * Playwright fixtures for authenticated test users.
 *
 * Provides pre-authenticated Page instances (alicePage, bobPage) using
 * storageState files generated by global-setup.ts.
 *
 * Also exposes seedData for accessing server/channel/user IDs in tests.
 *
 * Each page dismisses the announcement popup if it appears after navigation.
 */

import { test as base, type Page } from '@playwright/test'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import type { SeedData } from '../global-setup'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const AUTH_DIR = path.resolve(__dirname, '../.auth')

async function dismissAnnouncements(page: Page): Promise<void> {
  const overlay = page.locator('[data-testid="announcement-overlay"]')
  if (await overlay.isVisible({ timeout: 2000 }).catch(() => false)) {
    const markAllBtn = page.locator('[data-testid="announcement-mark-all-read"]')
    if (await markAllBtn.isVisible({ timeout: 1000 }).catch(() => false)) {
      await markAllBtn.click()
    } else {
      const markReadBtns = page.locator('[data-testid="announcement-mark-read"]')
      const count = await markReadBtns.count()
      for (let i = 0; i < count; i++) {
        await markReadBtns.first().click()
        await page.waitForTimeout(300)
      }
    }
    await overlay.waitFor({ state: 'hidden', timeout: 5000 }).catch(() => {})
  }
}

type AuthFixtures = {
  alicePage: Page
  bobPage: Page
  seedData: SeedData
}

export const test = base.extend<AuthFixtures>({
  alicePage: async ({ browser }, use) => {
    const stateFile = path.resolve(AUTH_DIR, 'alice.json')
    if (!fs.existsSync(stateFile)) {
      throw new Error(
        `Alice storageState not found at ${stateFile}. Did globalSetup run successfully?`,
      )
    }
    const ctx = await browser.newContext({ storageState: stateFile })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  bobPage: async ({ browser }, use) => {
    const stateFile = path.resolve(AUTH_DIR, 'bob.json')
    if (!fs.existsSync(stateFile)) {
      throw new Error(
        `Bob storageState not found at ${stateFile}. Did globalSetup run successfully?`,
      )
    }
    const ctx = await browser.newContext({ storageState: stateFile })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  seedData: async ({}, use) => {
    const seedPath = path.resolve(AUTH_DIR, 'seed-data.json')
    if (!fs.existsSync(seedPath)) {
      throw new Error(
        `Seed data not found at ${seedPath}. Did globalSetup run successfully?`,
      )
    }
    const data: SeedData = JSON.parse(fs.readFileSync(seedPath, 'utf-8'))
    await use(data)
  },
})

export { dismissAnnouncements }
export { expect } from '@playwright/test'
