/**
 * Playwright fixtures for authenticated test users.
 *
 * Provides pre-authenticated Page instances (alicePage, bobPage) using
 * storageState files generated by global-setup.ts.
 *
 * Also exposes seedData for accessing server/channel/user IDs in tests.
 *
 * Each page dismisses the announcement popup if it appears after navigation.
 */

import { test as base, type Page } from '@playwright/test'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import type { SeedData } from '../global-setup'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const AUTH_DIR = path.resolve(__dirname, '../.auth')

async function dismissAnnouncements(page: Page): Promise<void> {
  // Wait for the page to stabilize so the async announcement RPC completes
  await page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {})

  const overlay = page.locator('[data-testid="announcement-overlay"]')

  // The popup loads via an async RPC - give it time to appear
  const isVisible = await overlay.isVisible({ timeout: 5000 }).catch(() => false)
  if (!isVisible) return

  // Click every "Mark as read" button until the overlay disappears
  // (handles both single and multiple announcements)
  for (let attempt = 0; attempt < 10; attempt++) {
    if (!(await overlay.isVisible().catch(() => false))) break

    const markAllBtn = page.locator('[data-testid="announcement-mark-all-read"]')
    if (await markAllBtn.isVisible({ timeout: 500 }).catch(() => false)) {
      await markAllBtn.click()
      break
    }

    const markReadBtn = page.locator('[data-testid="announcement-mark-read"]').first()
    if (await markReadBtn.isVisible({ timeout: 500 }).catch(() => false)) {
      await markReadBtn.click()
      await page.waitForTimeout(500)
    } else {
      // No buttons found - click overlay background to dismiss
      await overlay.click({ position: { x: 5, y: 5 } }).catch(() => {})
      break
    }
  }

  await overlay.waitFor({ state: 'hidden', timeout: 5000 }).catch(() => {})
}

type AuthFixtures = {
  alicePage: Page
  bobPage: Page
  seedData: SeedData
}

export const test = base.extend<AuthFixtures>({
  alicePage: async ({ browser }, use) => {
    const stateFile = path.resolve(AUTH_DIR, 'alice.json')
    if (!fs.existsSync(stateFile)) {
      throw new Error(
        `Alice storageState not found at ${stateFile}. Did globalSetup run successfully?`,
      )
    }
    const ctx = await browser.newContext({ storageState: stateFile })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  bobPage: async ({ browser }, use) => {
    const stateFile = path.resolve(AUTH_DIR, 'bob.json')
    if (!fs.existsSync(stateFile)) {
      throw new Error(
        `Bob storageState not found at ${stateFile}. Did globalSetup run successfully?`,
      )
    }
    const ctx = await browser.newContext({ storageState: stateFile })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  // eslint-disable-next-line no-empty-pattern
  seedData: async ({}, use) => {
    const seedPath = path.resolve(AUTH_DIR, 'seed-data.json')
    if (!fs.existsSync(seedPath)) {
      throw new Error(
        `Seed data not found at ${seedPath}. Did globalSetup run successfully?`,
      )
    }
    const data: SeedData = JSON.parse(fs.readFileSync(seedPath, 'utf-8'))
    await use(data)
  },
})

export { dismissAnnouncements }
export { expect } from '@playwright/test'
