-- Account security: two-factor enforcement in the database, recovery codes generated and
-- rate-limited server-side, session listing and revocation, security notices, data export,
-- and account deletion that re-authenticates and federates a Delete for the actor.
--
-- Assurance. GoTrue issues an aal1 session for a correct password before the TOTP
-- challenge, and PostgREST accepted it: the second factor gated the web UI only. GoTrue
-- v2.182.1 keeps a session at aal2 once a factor is verified and deletes the account's
-- other aal1 sessions on every successful verify, so a legitimate session of an enrolled
-- account is aal2. An aal1 one is mid-challenge or a password-only client.
--   session_meets_aal()            false for an authenticated request of an account with a
--                                  verified factor whose token is not aal2.
--   enforce_request_assurance()    PostgREST db-pre-request. 401 session_revoked when the
--                                  token's session_id no longer exists in auth.sessions;
--                                  403 insufficient_aal when session_meets_aal() is false.
--                                  /rpc/redeem_recovery_code_and_disable_mfa stays open.
--   restrictive policies           public.messages SELECT (postgres_changes),
--                                  realtime.messages (private channels), storage.objects.
--                                  The paths that bypass PostgREST.
-- pgrst.db_pre_request is set on the authenticator role and read on 'reload config'.
-- Dropping enforce_request_assurance() while the setting names it fails every request.
--
-- Recovery codes. Ten codes of ten Crockford base32 characters (50 bits), generated by
-- generate_mfa_recovery_codes() at aal2 within ten minutes of a TOTP verify, returned once,
-- stored as SHA-256 of the normalised code. Normalisation strips separators, upper-cases and
-- maps O->0, I/L->1; codes issued before this file are upper-case hex and normalise to
-- themselves. Five failed codes per account per fifteen minutes, then PT429. A verified
-- factor's removal deletes the account's codes.
--
-- Sessions. list_my_sessions() and revoke_my_session() read and delete the caller's
-- auth.sessions rows; refresh tokens cascade. push_subscriptions.session_id is written by
-- the federation backend at subscribe time, and a deleted session takes its push rows.
--
-- Security notices. Triggers on auth.sessions, auth.mfa_factors and auth.users insert
-- notifications of type 'security': a sign-in while another session exists, 2FA enabled or
-- disabled, password changed. Recovery-code use and regeneration notify from the RPCs. Each
-- trigger swallows its own errors so a GoTrue write never fails on account of a notice.
--
-- Export. request_my_data_export() returns everything except messages and records an export
-- valid for an hour; export_my_messages() pages the caller's own messages under it. Ten
-- minutes between exports, five per day. Key material, hashes, tokens and push endpoints
-- are not exported; DMs carry the caller's own messages and participant handles only.
--
-- Ownership. Every function defined here is owned by postgres, as on a fresh install. Run
-- as supabase_admin, CREATE leaves new functions owned by supabase_admin and CREATE OR
-- REPLACE keeps an existing function's owner, so a postgres-owned definer would call a
-- supabase_admin-owned helper whose PUBLIC grant is revoked (42501). New tables are owned
-- by postgres. The tables the definers read and write are checked for the privileges
-- postgres needs; missing ones are granted and the migration fails if a grant does not
-- take. mfa_recovery_codes is reachable through these functions only: no client or
-- service_role grant, as on production.
--
-- Deletion. delete_my_account(p_password) checks the password against auth.users with
-- pgcrypto (bcrypt, $2a$), five failures per fifteen minutes, shared with
-- verify_my_password() which gates the password-change form; accounts without a password
-- need a sign-in within ten minutes; enrolled accounts need a TOTP verify within ten
-- minutes. Content stays, attributed to the tombstoned profile (deleted_at set). The actor's
-- key, URI and the inboxes of its remote followers and followees go to deleted_actors and an
-- 'account-deleted' job sends the Delete and removes avatar and banner objects. Bots are
-- deactivated and their tokens revoked. The zero-argument delete_my_account() is replaced:
-- a call without a password answers password_required.

BEGIN;

SET LOCAL lock_timeout = '3s';

-- ---------------------------------------------------------------------------
-- Tables and columns
-- ---------------------------------------------------------------------------

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
COMMENT ON COLUMN public.profiles.deleted_at IS
    'Set when the account was deleted; the row remains as the author of retained content.';

ALTER TABLE public.push_subscriptions ADD COLUMN IF NOT EXISTS session_id uuid;
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_session
    ON public.push_subscriptions (session_id) WHERE session_id IS NOT NULL;
COMMENT ON COLUMN public.push_subscriptions.session_id IS
    'auth.sessions id of the sign-in that registered the target; removed with that session.';

CREATE TABLE IF NOT EXISTS public.account_security_attempts (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    auth_user_id uuid NOT NULL,
    kind text NOT NULL,
    succeeded boolean NOT NULL,
    attempted_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT account_security_attempts_kind_check CHECK (kind IN ('recovery_code', 'password'))
);
CREATE INDEX IF NOT EXISTS idx_account_security_attempts_lookup
    ON public.account_security_attempts (auth_user_id, kind, attempted_at DESC);
ALTER TABLE public.account_security_attempts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS account_security_attempts_service_role ON public.account_security_attempts;
CREATE POLICY account_security_attempts_service_role ON public.account_security_attempts
    AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
REVOKE ALL ON public.account_security_attempts FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.account_security_attempts TO service_role;
COMMENT ON TABLE public.account_security_attempts IS
    'Recovery-code and password checks per account; failures inside 15 minutes cap further attempts.';

CREATE TABLE IF NOT EXISTS public.account_data_exports (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    requested_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL DEFAULT now() + interval '1 hour'
);
CREATE INDEX IF NOT EXISTS idx_account_data_exports_profile
    ON public.account_data_exports (profile_id, requested_at DESC);
ALTER TABLE public.account_data_exports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS account_data_exports_service_role ON public.account_data_exports;
CREATE POLICY account_data_exports_service_role ON public.account_data_exports
    AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
REVOKE ALL ON public.account_data_exports FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.account_data_exports TO service_role;
COMMENT ON TABLE public.account_data_exports IS
    'One row per data export; export_my_messages pages only under an unexpired row.';

CREATE TABLE IF NOT EXISTS public.deleted_actors (
    profile_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    username text NOT NULL,
    domain text NOT NULL,
    actor_uri text NOT NULL,
    private_key text,
    inboxes text[] NOT NULL DEFAULT '{}',
    deleted_at timestamptz NOT NULL DEFAULT now(),
    delivered_at timestamptz,
    key_purge_after timestamptz NOT NULL DEFAULT now() + interval '7 days'
);
CREATE INDEX IF NOT EXISTS idx_deleted_actors_handle
    ON public.deleted_actors (lower(username), domain);
ALTER TABLE public.deleted_actors ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS deleted_actors_service_role ON public.deleted_actors;
CREATE POLICY deleted_actors_service_role ON public.deleted_actors
    AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
REVOKE ALL ON public.deleted_actors FROM PUBLIC, anon, authenticated;
GRANT SELECT, UPDATE ON public.deleted_actors TO service_role;
COMMENT ON TABLE public.deleted_actors IS
    'Local actors whose accounts were deleted: signing key (until key_purge_after) and inboxes for the ActivityPub Delete; the handle answers 410.';

-- ---------------------------------------------------------------------------
-- Assurance
-- ---------------------------------------------------------------------------

-- PostgREST v12+ and Realtime set request.jwt.claims; auth.jwt() is absent from images
-- whose auth schema GoTrue has not migrated.
CREATE OR REPLACE FUNCTION public.current_jwt_claims()
RETURNS jsonb
LANGUAGE sql
STABLE
SET search_path = pg_catalog, pg_temp
AS $$
    SELECT nullif(current_setting('request.jwt.claims', true), '')::jsonb;
$$;

CREATE OR REPLACE FUNCTION public.mfa_enabled_for(p_auth_user_id uuid)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
BEGIN
    IF p_auth_user_id IS NULL OR to_regclass('auth.mfa_factors') IS NULL THEN
        RETURN false;
    END IF;
    RETURN EXISTS (SELECT 1 FROM auth.mfa_factors f
                    WHERE f.user_id = p_auth_user_id AND f.status = 'verified');
END;
$$;

-- request.jwt.claims carries role; the test harness sets only the role GUC, which a
-- SECURITY DEFINER body still reads as the session's SET ROLE.
CREATE OR REPLACE FUNCTION public.session_meets_aal()
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    v_claims jsonb := public.current_jwt_claims();
    v_role text;
BEGIN
    v_role := coalesce(v_claims ->> 'role', nullif(current_setting('role', true), 'none'));
    IF v_role IS DISTINCT FROM 'authenticated' OR v_claims ->> 'aal' = 'aal2' THEN
        RETURN true;
    END IF;
    RETURN NOT public.mfa_enabled_for(auth.uid());
END;
$$;

-- True when the token's amr lists p_method (any method when NULL) authenticated within
-- p_max_age. GoTrue writes amr as [{method, timestamp}] with timestamp in epoch seconds.
CREATE OR REPLACE FUNCTION public.session_step_up_fresh(p_method text, p_max_age interval)
RETURNS boolean
LANGUAGE sql
STABLE
SET search_path = pg_catalog, public, pg_temp
AS $$
    SELECT EXISTS (
        SELECT 1
          FROM jsonb_array_elements(
                 CASE WHEN jsonb_typeof(public.current_jwt_claims() -> 'amr') = 'array'
                      THEN public.current_jwt_claims() -> 'amr' ELSE '[]'::jsonb END) e
         WHERE jsonb_typeof(e) = 'object'
           AND (p_method IS NULL OR e ->> 'method' = p_method)
           AND (e ->> 'timestamp') ~ '^[0-9]+$'
           AND (e ->> 'timestamp')::bigint >= extract(epoch FROM now() - p_max_age)::bigint
    );
$$;

CREATE OR REPLACE FUNCTION public.enforce_request_assurance()
RETURNS void
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    v_claims jsonb := public.current_jwt_claims();
    v_sid text;
BEGIN
    IF v_claims IS NULL OR v_claims ->> 'role' IS DISTINCT FROM 'authenticated' THEN
        RETURN;
    END IF;

    v_sid := v_claims ->> 'session_id';
    IF v_sid ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
       AND to_regclass('auth.sessions') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM auth.sessions s WHERE s.id = v_sid::uuid) THEN
        RAISE SQLSTATE 'PT401' USING
            MESSAGE = 'session_revoked',
            HINT = 'This session was signed out. Sign in again.';
    END IF;

    IF public.session_meets_aal()
       OR current_setting('request.path', true) = '/rpc/redeem_recovery_code_and_disable_mfa' THEN
        RETURN;
    END IF;

    RAISE SQLSTATE 'PT403' USING
        MESSAGE = 'insufficient_aal',
        DETAIL = 'This account requires two-factor authentication.',
        HINT = 'Complete the two-factor challenge.';
END;
$$;

COMMENT ON FUNCTION public.enforce_request_assurance() IS
    'PostgREST db-pre-request (authenticator: pgrst.db_pre_request). Every PostgREST request fails while the setting names a missing function.';

REVOKE ALL ON FUNCTION public.current_jwt_claims() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.mfa_enabled_for(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.session_step_up_fresh(text, interval) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.session_meets_aal() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.enforce_request_assurance() FROM PUBLIC, anon, authenticated;
-- PostgREST runs the pre-request function as the request role; policies run
-- session_meets_aal() as the querying role.
GRANT EXECUTE ON FUNCTION public.session_meets_aal() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.enforce_request_assurance() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.mfa_enabled_for(uuid) TO service_role;

DROP POLICY IF EXISTS messages_session_aal ON public.messages;
CREATE POLICY messages_session_aal ON public.messages
    AS RESTRICTIVE FOR SELECT TO authenticated
    USING ((SELECT public.session_meets_aal()));

DO $$
BEGIN
    IF to_regclass('realtime.messages') IS NULL THEN
        RAISE NOTICE 'realtime.messages absent, aal policy skipped';
        RETURN;
    END IF;
    DROP POLICY IF EXISTS realtime_messages_session_aal ON realtime.messages;
    CREATE POLICY realtime_messages_session_aal ON realtime.messages
        AS RESTRICTIVE FOR ALL TO authenticated
        USING ((SELECT public.session_meets_aal()))
        WITH CHECK ((SELECT public.session_meets_aal()));
    RAISE NOTICE 'realtime.messages aal policy installed';
EXCEPTION WHEN insufficient_privilege THEN
    RAISE NOTICE 'realtime.messages aal policy skipped: %', SQLERRM;
END;
$$;

DO $$
BEGIN
    IF to_regclass('storage.objects') IS NULL THEN
        RAISE NOTICE 'storage.objects absent, aal policy skipped';
        RETURN;
    END IF;
    DROP POLICY IF EXISTS storage_objects_session_aal ON storage.objects;
    CREATE POLICY storage_objects_session_aal ON storage.objects
        AS RESTRICTIVE FOR ALL TO authenticated
        USING ((SELECT public.session_meets_aal()))
        WITH CHECK ((SELECT public.session_meets_aal()));
    RAISE NOTICE 'storage.objects aal policy installed';
EXCEPTION WHEN insufficient_privilege THEN
    RAISE NOTICE 'storage.objects aal policy skipped: %', SQLERRM;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticator') THEN
        RAISE NOTICE 'authenticator role absent, pgrst.db_pre_request not set';
        RETURN;
    END IF;
    ALTER ROLE authenticator SET pgrst.db_pre_request TO 'public.enforce_request_assurance';
    RAISE NOTICE 'authenticator: pgrst.db_pre_request = public.enforce_request_assurance';
EXCEPTION WHEN insufficient_privilege THEN
    RAISE NOTICE 'pgrst.db_pre_request not set: %', SQLERRM;
END;
$$;

-- ---------------------------------------------------------------------------
-- Attempt budget and security notices
-- ---------------------------------------------------------------------------

-- Raises PT429 once five checks of p_kind failed inside fifteen minutes. DETAIL carries
-- retry_after=<seconds>.
CREATE OR REPLACE FUNCTION public.assert_security_attempt_budget(p_auth_user_id uuid, p_kind text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    v_failures integer;
    v_oldest timestamptz;
BEGIN
    SELECT count(*), min(a.attempted_at) INTO v_failures, v_oldest
      FROM public.account_security_attempts a
     WHERE a.auth_user_id = p_auth_user_id
       AND a.kind = p_kind
       AND NOT a.succeeded
       AND a.attempted_at > now() - interval '15 minutes';

    IF v_failures >= 5 THEN
        RAISE SQLSTATE 'PT429' USING
            MESSAGE = 'too_many_attempts',
            DETAIL = 'retry_after=' || greatest(1, ceil(extract(epoch FROM
                         v_oldest + interval '15 minutes' - now())))::bigint;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_security_attempt(p_auth_user_id uuid, p_kind text, p_succeeded boolean)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
BEGIN
    DELETE FROM public.account_security_attempts a
     WHERE a.auth_user_id = p_auth_user_id AND a.attempted_at < now() - interval '1 day';
    INSERT INTO public.account_security_attempts (auth_user_id, kind, succeeded)
    VALUES (p_auth_user_id, p_kind, p_succeeded);
END;
$$;

-- Notification of type 'security' for the live profile of an auth user. data.event is one
-- of new_sign_in, mfa_enabled, mfa_disabled, recovery_code_used,
-- recovery_codes_regenerated, password_changed.
CREATE OR REPLACE FUNCTION public.record_security_notice(p_auth_user_id uuid, p_event text, p_data jsonb DEFAULT '{}'::jsonb)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
BEGIN
    INSERT INTO public.notifications (user_id, type, data)
    SELECT p.id, 'security',
           jsonb_build_object('event', p_event, 'at', now()) || coalesce(p_data, '{}'::jsonb)
      FROM public.profiles p
     WHERE p.auth_user_id = p_auth_user_id
       AND p.deleted_at IS NULL
     LIMIT 1;
END;
$$;

REVOKE ALL ON FUNCTION public.assert_security_attempt_budget(uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.record_security_attempt(uuid, text, boolean) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.record_security_notice(uuid, text, jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_security_notice(uuid, text, jsonb) TO service_role;

-- Re-entry of the current password before a password change. GoTrue's PUT /user takes no
-- current password, so this gates the settings form, not the API. Shares the password
-- budget with delete_my_account.
CREATE OR REPLACE FUNCTION public.verify_my_password(p_password text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    v_uid uuid := auth.uid();
    v_hash text;
    v_ok boolean;
BEGIN
    IF v_uid IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;
    SELECT u.encrypted_password INTO v_hash FROM auth.users u WHERE u.id = v_uid;
    IF v_hash IS NULL OR v_hash NOT LIKE '$2%' THEN
        RAISE EXCEPTION 'no_password' USING ERRCODE = 'P0001';
    END IF;
    PERFORM public.assert_security_attempt_budget(v_uid, 'password');
    v_ok := extensions.crypt(coalesce(p_password, ''), v_hash) = v_hash;
    PERFORM public.record_security_attempt(v_uid, 'password', v_ok);
    RETURN v_ok;
END;
$$;

REVOKE ALL ON FUNCTION public.verify_my_password(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.verify_my_password(text) TO authenticated;

-- ---------------------------------------------------------------------------
-- Recovery codes
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.normalize_recovery_code(p_code text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog, pg_temp
AS $$
    SELECT translate(upper(regexp_replace(coalesce(p_code, ''), '[^0-9A-Za-z]', '', 'g')), 'OIL', '011');
$$;

CREATE OR REPLACE FUNCTION public.hash_recovery_code(p_code text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog, public, pg_temp
AS $$
    SELECT encode(extensions.digest(convert_to(public.normalize_recovery_code(p_code), 'UTF8'), 'sha256'), 'hex');
$$;

REVOKE ALL ON FUNCTION public.normalize_recovery_code(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.hash_recovery_code(text) FROM PUBLIC, anon, authenticated;

-- Owner key for new mfa_recovery_codes rows: auth uid where the table's foreign key points
-- at auth.users (production), profile id where it points at profiles (baseline).
CREATE OR REPLACE FUNCTION public.recovery_code_owner(p_auth_user_id uuid, p_profile_id uuid)
RETURNS uuid
LANGUAGE sql
STABLE
SET search_path = pg_catalog, public, pg_temp
AS $$
    SELECT CASE WHEN EXISTS (
               SELECT 1 FROM pg_constraint c
                WHERE c.conrelid = 'public.mfa_recovery_codes'::regclass
                  AND c.contype = 'f'
                  AND c.confrelid = 'auth.users'::regclass)
           THEN p_auth_user_id ELSE p_profile_id END;
$$;

REVOKE ALL ON FUNCTION public.recovery_code_owner(uuid, uuid) FROM PUBLIC, anon, authenticated;

-- Rows are keyed by profile id (baseline FK) or auth uid (production FK to auth.users);
-- local profiles carry id = auth_user_id, so both keys are matched.
CREATE OR REPLACE FUNCTION public.generate_mfa_recovery_codes()
RETURNS text[]
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    c_alphabet constant text := '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
    v_uid uuid := auth.uid();
    v_profile uuid := public.get_current_profile_id();
    v_batch uuid := gen_random_uuid();
    v_codes text[] := '{}';
    v_bytes bytea;
    v_code text;
    i integer;
    j integer;
BEGIN
    IF v_uid IS NULL OR v_profile IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;
    IF NOT public.mfa_enabled_for(v_uid) THEN
        RAISE EXCEPTION 'mfa_not_enabled' USING ERRCODE = 'P0001';
    END IF;
    IF public.current_jwt_claims() ->> 'aal' IS DISTINCT FROM 'aal2'
       OR NOT public.session_step_up_fresh('totp', interval '10 minutes') THEN
        RAISE SQLSTATE 'PT403' USING
            MESSAGE = 'step_up_required',
            HINT = 'Verify an authenticator code first.';
    END IF;

    FOR i IN 1..10 LOOP
        v_bytes := extensions.gen_random_bytes(10);
        v_code := '';
        FOR j IN 0..9 LOOP
            -- 256 is a multiple of 32: the low five bits are uniform.
            v_code := v_code || substr(c_alphabet, (get_byte(v_bytes, j) & 31) + 1, 1);
        END LOOP;
        v_codes := v_codes || (substr(v_code, 1, 5) || '-' || substr(v_code, 6, 5));
    END LOOP;

    DELETE FROM public.mfa_recovery_codes r WHERE r.user_id IN (v_profile, v_uid);
    INSERT INTO public.mfa_recovery_codes (user_id, code_hash, batch_id)
    SELECT public.recovery_code_owner(v_uid, v_profile), public.hash_recovery_code(c), v_batch
      FROM unnest(v_codes) c;

    PERFORM public.record_security_notice(v_uid, 'recovery_codes_regenerated');
    RETURN v_codes;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_mfa_recovery_status()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    v_uid uuid := auth.uid();
    v_profile uuid := public.get_current_profile_id();
    v_total integer;
    v_remaining integer;
    v_generated timestamptz;
BEGIN
    IF v_uid IS NULL OR v_profile IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;
    SELECT count(*), count(*) FILTER (WHERE r.used_at IS NULL), max(r.created_at)
      INTO v_total, v_remaining, v_generated
      FROM public.mfa_recovery_codes r
     WHERE r.user_id IN (v_profile, v_uid);
    RETURN jsonb_build_object(
        'mfa_enabled', public.mfa_enabled_for(v_uid),
        'total', v_total,
        'remaining', v_remaining,
        'generated_at', v_generated);
END;
$$;

-- Client-supplied codes, kept for released clients that generate at enrolment. Requires
-- aal2 when a factor is verified: an aal1 session must not be able to plant codes it can
-- then redeem.
CREATE OR REPLACE FUNCTION public.save_recovery_codes(p_user_id uuid, p_codes text[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    v_uid uuid := auth.uid();
    v_caller uuid := public.get_current_profile_id();
    v_batch uuid := gen_random_uuid();
    v_code text;
BEGIN
    IF v_uid IS NULL OR v_caller IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;
    IF p_user_id IS DISTINCT FROM v_caller AND p_user_id IS DISTINCT FROM v_uid THEN
        RAISE EXCEPTION 'Permission denied: can only save your own recovery codes' USING ERRCODE = '42501';
    END IF;
    IF public.mfa_enabled_for(v_uid) AND public.current_jwt_claims() ->> 'aal' IS DISTINCT FROM 'aal2' THEN
        RAISE SQLSTATE 'PT403' USING MESSAGE = 'insufficient_aal';
    END IF;
    IF coalesce(array_length(p_codes, 1), 0) NOT BETWEEN 1 AND 20 THEN
        RAISE EXCEPTION 'Expected between 1 and 20 recovery codes' USING ERRCODE = '22023';
    END IF;
    FOREACH v_code IN ARRAY p_codes LOOP
        IF length(public.normalize_recovery_code(v_code)) NOT BETWEEN 8 AND 32 THEN
            RAISE EXCEPTION 'Recovery codes must be 8 to 32 letters or digits' USING ERRCODE = '22023';
        END IF;
    END LOOP;

    DELETE FROM public.mfa_recovery_codes r WHERE r.user_id IN (v_caller, v_uid);
    INSERT INTO public.mfa_recovery_codes (user_id, code_hash, batch_id)
    SELECT public.recovery_code_owner(v_uid, v_caller), public.hash_recovery_code(c), v_batch
      FROM unnest(p_codes) c;
END;
$$;

-- Marks a code used. Does not touch factors. Budgeted with redemption.
CREATE OR REPLACE FUNCTION public.verify_recovery_code(p_user_id uuid, p_code text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    v_uid uuid := auth.uid();
    v_profile uuid := public.get_current_profile_id();
    v_code_id uuid;
BEGIN
    IF v_uid IS NULL THEN
        RAISE EXCEPTION 'Unauthorized: verify_recovery_code requires an authenticated session'
            USING ERRCODE = '42501';
    END IF;
    IF p_user_id IS DISTINCT FROM v_uid THEN
        RAISE EXCEPTION 'Unauthorized: cannot verify recovery codes for another user'
            USING ERRCODE = '42501';
    END IF;

    PERFORM public.assert_security_attempt_budget(v_uid, 'recovery_code');

    UPDATE public.mfa_recovery_codes r
       SET used_at = now()
     WHERE r.id = (SELECT c.id FROM public.mfa_recovery_codes c
                    WHERE c.user_id IN (v_profile, v_uid)
                      AND c.code_hash = public.hash_recovery_code(p_code)
                      AND c.used_at IS NULL
                    LIMIT 1
                    FOR UPDATE SKIP LOCKED)
    RETURNING r.id INTO v_code_id;

    PERFORM public.record_security_attempt(v_uid, 'recovery_code', v_code_id IS NOT NULL);
    IF v_code_id IS NOT NULL THEN
        PERFORM public.record_security_notice(v_uid, 'recovery_code_used');
    END IF;
    RETURN v_code_id IS NOT NULL;
END;
$$;

-- Sign-in with a lost authenticator: consumes a code and removes the account's factors in
-- one transaction. Reachable below aal2 (enforce_request_assurance allows its path).
CREATE OR REPLACE FUNCTION public.redeem_recovery_code_and_disable_mfa(p_code text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    v_uid uuid := auth.uid();
    v_profile uuid := public.get_current_profile_id();
    v_code_id uuid;
BEGIN
    IF v_uid IS NULL THEN
        RAISE EXCEPTION 'Unauthorized: requires an authenticated session' USING ERRCODE = '42501';
    END IF;
    IF length(public.normalize_recovery_code(p_code)) < 8 THEN
        RETURN false;
    END IF;

    PERFORM public.assert_security_attempt_budget(v_uid, 'recovery_code');

    UPDATE public.mfa_recovery_codes r
       SET used_at = now()
     WHERE r.id = (SELECT c.id FROM public.mfa_recovery_codes c
                    WHERE c.user_id IN (v_profile, v_uid)
                      AND c.code_hash = public.hash_recovery_code(p_code)
                      AND c.used_at IS NULL
                    LIMIT 1
                    FOR UPDATE SKIP LOCKED)
    RETURNING r.id INTO v_code_id;

    PERFORM public.record_security_attempt(v_uid, 'recovery_code', v_code_id IS NOT NULL);
    IF v_code_id IS NULL THEN
        RETURN false;
    END IF;

    PERFORM set_config('harmony.mfa_disable_reason', 'recovery_code', true);
    IF to_regclass('auth.mfa_factors') IS NOT NULL THEN
        DELETE FROM auth.mfa_factors f WHERE f.user_id = v_uid;
    END IF;
    DELETE FROM public.mfa_recovery_codes r WHERE r.user_id IN (v_profile, v_uid);
    RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.generate_mfa_recovery_codes() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_mfa_recovery_status() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.save_recovery_codes(uuid, text[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.verify_recovery_code(uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.redeem_recovery_code_and_disable_mfa(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.generate_mfa_recovery_codes() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_mfa_recovery_status() TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_recovery_codes(uuid, text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_recovery_code(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_recovery_code_and_disable_mfa(text) TO authenticated;

-- Production carries count_unused_recovery_codes(uuid), which reports any account's count.
DO $$
DECLARE
    fn regprocedure;
BEGIN
    FOR fn IN SELECT p.oid::regprocedure FROM pg_proc p
               WHERE p.pronamespace = 'public'::regnamespace
                 AND p.proname = 'count_unused_recovery_codes'
    LOOP
        EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated', fn);
        RAISE NOTICE '% revoked from clients', fn;
    END LOOP;
END;
$$;

-- ---------------------------------------------------------------------------
-- Sessions
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.list_my_sessions()
RETURNS TABLE (
    id uuid,
    created_at timestamptz,
    last_active_at timestamptz,
    user_agent text,
    ip text,
    aal text,
    is_current boolean,
    push_transports text[]
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
#variable_conflict use_column
DECLARE
    v_uid uuid := auth.uid();
    v_profile uuid := public.get_current_profile_id();
    v_current text := public.current_jwt_claims() ->> 'session_id';
BEGIN
    IF v_uid IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;
    RETURN QUERY
    SELECT s.id,
           s.created_at,
           greatest(s.created_at, s.updated_at, s.refreshed_at AT TIME ZONE 'UTC'),
           s.user_agent,
           host(s.ip),
           s.aal::text,
           s.id::text = v_current,
           coalesce((SELECT array_agg(DISTINCT ps.transport ORDER BY ps.transport)
                       FROM public.push_subscriptions ps
                      WHERE ps.session_id = s.id AND ps.user_id = v_profile), '{}'::text[])
      FROM auth.sessions s
     WHERE s.user_id = v_uid
       AND (s.not_after IS NULL OR s.not_after > now())
     ORDER BY (s.id::text = v_current) DESC,
              greatest(s.created_at, s.updated_at, s.refreshed_at AT TIME ZONE 'UTC') DESC NULLS LAST;
END;
$$;

CREATE OR REPLACE FUNCTION public.revoke_my_session(p_session_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    v_uid uuid := auth.uid();
    v_count integer;
BEGIN
    IF v_uid IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;
    DELETE FROM auth.sessions s WHERE s.id = p_session_id AND s.user_id = v_uid;
    GET DIAGNOSTICS v_count = ROW_COUNT;
    RETURN v_count > 0;
END;
$$;

REVOKE ALL ON FUNCTION public.list_my_sessions() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.revoke_my_session(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.list_my_sessions() TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_my_session(uuid) TO authenticated;

-- ---------------------------------------------------------------------------
-- Triggers on GoTrue tables
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.on_auth_session_created()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM auth.sessions s WHERE s.user_id = NEW.user_id AND s.id <> NEW.id) THEN
        PERFORM public.record_security_notice(NEW.user_id, 'new_sign_in', jsonb_build_object(
            'session_id', NEW.id,
            'user_agent', left(NEW.user_agent, 512),
            'ip', host(NEW.ip)));
    END IF;
    RETURN NULL;
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'on_auth_session_created: %', SQLERRM;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.on_auth_session_deleted()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
BEGIN
    DELETE FROM public.push_subscriptions ps WHERE ps.session_id = OLD.id;
    RETURN NULL;
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'on_auth_session_deleted: %', SQLERRM;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.on_auth_mfa_factor_changed()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.status::text = 'verified' AND OLD.status::text IS DISTINCT FROM 'verified' THEN
            PERFORM public.record_security_notice(NEW.user_id, 'mfa_enabled',
                jsonb_build_object('factor_type', NEW.factor_type::text));
        END IF;
    ELSIF OLD.status::text = 'verified' AND NOT public.mfa_enabled_for(OLD.user_id) THEN
        DELETE FROM public.mfa_recovery_codes r
         WHERE r.user_id = OLD.user_id
            OR r.user_id IN (SELECT p.id FROM public.profiles p WHERE p.auth_user_id = OLD.user_id);
        PERFORM public.record_security_notice(OLD.user_id, 'mfa_disabled', jsonb_build_object(
            'factor_type', OLD.factor_type::text,
            'reason', nullif(current_setting('harmony.mfa_disable_reason', true), '')));
    END IF;
    RETURN NULL;
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'on_auth_mfa_factor_changed: %', SQLERRM;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.on_auth_password_changed()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
BEGIN
    PERFORM public.record_security_notice(NEW.id, 'password_changed');
    RETURN NULL;
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'on_auth_password_changed: %', SQLERRM;
    RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION public.on_auth_session_created() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.on_auth_session_deleted() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.on_auth_mfa_factor_changed() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.on_auth_password_changed() FROM PUBLIC, anon, authenticated;

-- GoTrue creates sessions and mfa_factors at service start; a bare Postgres image has
-- neither. One block per table so a privilege failure on one leaves the others installed.
DO $$
BEGIN
    IF to_regclass('auth.sessions') IS NULL THEN
        RAISE NOTICE 'auth.sessions absent, session triggers skipped';
        RETURN;
    END IF;
    DROP TRIGGER IF EXISTS harmony_session_created ON auth.sessions;
    CREATE TRIGGER harmony_session_created AFTER INSERT ON auth.sessions
        FOR EACH ROW EXECUTE FUNCTION public.on_auth_session_created();
    DROP TRIGGER IF EXISTS harmony_session_deleted ON auth.sessions;
    CREATE TRIGGER harmony_session_deleted AFTER DELETE ON auth.sessions
        FOR EACH ROW EXECUTE FUNCTION public.on_auth_session_deleted();
    RAISE NOTICE 'auth.sessions triggers installed';
EXCEPTION WHEN insufficient_privilege THEN
    RAISE NOTICE 'auth.sessions triggers skipped: %', SQLERRM;
END;
$$;

DO $$
BEGIN
    IF to_regclass('auth.mfa_factors') IS NULL THEN
        RAISE NOTICE 'auth.mfa_factors absent, factor triggers skipped';
        RETURN;
    END IF;
    DROP TRIGGER IF EXISTS harmony_mfa_factor_verified ON auth.mfa_factors;
    CREATE TRIGGER harmony_mfa_factor_verified AFTER UPDATE OF status ON auth.mfa_factors
        FOR EACH ROW EXECUTE FUNCTION public.on_auth_mfa_factor_changed();
    DROP TRIGGER IF EXISTS harmony_mfa_factor_deleted ON auth.mfa_factors;
    CREATE TRIGGER harmony_mfa_factor_deleted AFTER DELETE ON auth.mfa_factors
        FOR EACH ROW EXECUTE FUNCTION public.on_auth_mfa_factor_changed();
    RAISE NOTICE 'auth.mfa_factors triggers installed';
EXCEPTION WHEN insufficient_privilege THEN
    RAISE NOTICE 'auth.mfa_factors triggers skipped: %', SQLERRM;
END;
$$;

DO $$
BEGIN
    DROP TRIGGER IF EXISTS harmony_password_changed ON auth.users;
    CREATE TRIGGER harmony_password_changed AFTER UPDATE OF encrypted_password ON auth.users
        FOR EACH ROW
        WHEN (OLD.encrypted_password IS DISTINCT FROM NEW.encrypted_password
              AND coalesce(OLD.encrypted_password, '') <> '')
        EXECUTE FUNCTION public.on_auth_password_changed();
    RAISE NOTICE 'auth.users password trigger installed';
EXCEPTION WHEN insufficient_privilege THEN
    RAISE NOTICE 'auth.users password trigger skipped: %', SQLERRM;
END;
$$;

-- ---------------------------------------------------------------------------
-- Data export
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.profile_handle(p_profile_id uuid)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
    SELECT jsonb_build_object('id', p.id, 'username', p.username, 'domain', p.domain,
                              'display_name', p.display_name, 'deleted', p.deleted_at IS NOT NULL)
      FROM public.profiles p WHERE p.id = p_profile_id;
$$;
REVOKE ALL ON FUNCTION public.profile_handle(uuid) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.request_my_data_export()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    v_uid uuid := auth.uid();
    v_profile uuid := public.get_current_profile_id();
    v_last timestamptz;
    v_today integer;
    v_export_id uuid;
    v_doc jsonb;
    v_media jsonb := '[]'::jsonb;
BEGIN
    IF v_uid IS NULL OR v_profile IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;

    SELECT max(e.requested_at), count(*) FILTER (WHERE e.requested_at > now() - interval '1 day')
      INTO v_last, v_today
      FROM public.account_data_exports e WHERE e.profile_id = v_profile;
    IF v_last > now() - interval '10 minutes' THEN
        RAISE SQLSTATE 'PT429' USING MESSAGE = 'export_rate_limited',
            DETAIL = 'retry_after=' || ceil(extract(epoch FROM v_last + interval '10 minutes' - now()))::bigint;
    END IF;
    IF v_today >= 5 THEN
        RAISE SQLSTATE 'PT429' USING MESSAGE = 'export_rate_limited',
            DETAIL = 'retry_after=' || ceil(extract(epoch FROM
                (SELECT min(e.requested_at) FROM public.account_data_exports e
                  WHERE e.profile_id = v_profile AND e.requested_at > now() - interval '1 day')
                + interval '1 day' - now()))::bigint;
    END IF;

    DELETE FROM public.account_data_exports e
     WHERE e.profile_id = v_profile AND e.requested_at < now() - interval '2 days';
    INSERT INTO public.account_data_exports (profile_id) VALUES (v_profile) RETURNING id INTO v_export_id;

    BEGIN
        SELECT coalesce(jsonb_agg(jsonb_build_object(
                   'bucket', o.bucket_id, 'name', o.name, 'created_at', o.created_at,
                   'size', o.metadata ->> 'size', 'mimetype', o.metadata ->> 'mimetype')
                   ORDER BY o.created_at), '[]'::jsonb)
          INTO v_media
          FROM storage.objects o
         WHERE o.bucket_id IN ('avatars', 'banners', 'user_media')
           AND (storage.foldername(o.name))[1] IN (v_uid::text, v_profile::text);
    EXCEPTION WHEN undefined_table OR undefined_function OR insufficient_privilege THEN
        v_media := '[]'::jsonb;
    END;

    v_doc := jsonb_build_object(
        'format', 'harmony-account-export',
        'version', 1,
        'export_id', v_export_id,
        'generated_at', now(),
        'account', (SELECT jsonb_build_object(
                        'auth_user_id', u.id, 'email', u.email,
                        'created_at', u.created_at, 'last_sign_in_at', u.last_sign_in_at,
                        'confirmed_at', u.confirmed_at,
                        'providers', u.raw_app_meta_data -> 'providers')
                      FROM auth.users u WHERE u.id = v_uid),
        'two_factor', jsonb_build_object(
            'enabled', public.mfa_enabled_for(v_uid),
            'recovery_codes_remaining', (SELECT count(*) FROM public.mfa_recovery_codes r
                                          WHERE r.user_id IN (v_profile, v_uid) AND r.used_at IS NULL)),
        'sessions', (SELECT coalesce(jsonb_agg(to_jsonb(s)), '[]'::jsonb) FROM public.list_my_sessions() s),
        'profile', (SELECT to_jsonb(p) - 'web_handle' FROM public.profiles p WHERE p.id = v_profile),
        'notification_preferences', (SELECT to_jsonb(n) - 'id' - 'user_id'
                                       FROM public.notification_preferences n WHERE n.user_id = v_profile LIMIT 1),
        'notification_overrides', (SELECT coalesce(jsonb_agg(to_jsonb(n) - 'user_id'), '[]'::jsonb)
                                     FROM public.notification_channels n WHERE n.user_id = v_profile),
        'server_folders', (SELECT coalesce(jsonb_agg(to_jsonb(f) - 'user_id'), '[]'::jsonb)
                             FROM public.server_folders f WHERE f.user_id = v_profile),
        -- Whole row: production's user_servers lacks columns a fresh install has (nickname).
        'servers', (SELECT coalesce(jsonb_agg((to_jsonb(us) - 'id' - 'user_id') || jsonb_build_object(
                        'name', s.name, 'owner', s.owner = v_profile) ORDER BY us.created_at), '[]'::jsonb)
                      FROM public.user_servers us
                      JOIN public.servers s ON s.id = us.server_id
                     WHERE us.user_id = v_profile),
        'servers_owned', (SELECT coalesce(jsonb_agg(jsonb_build_object(
                              'id', s.id, 'name', s.name, 'description', s.description,
                              'created_at', s.created_at)), '[]'::jsonb)
                            FROM public.servers s WHERE s.owner = v_profile),
        'conversations', (SELECT coalesce(jsonb_agg(jsonb_build_object(
                              'id', c.id, 'type', c.type, 'name', c.name, 'created_at', c.created_at,
                              'joined_at', cp.joined_at, 'left_at', cp.left_at,
                              'participants', (SELECT coalesce(jsonb_agg(public.profile_handle(o.user_id)), '[]'::jsonb)
                                                 FROM public.conversation_participants o
                                                WHERE o.conversation_id = c.id))
                              ORDER BY c.created_at), '[]'::jsonb)
                            FROM public.conversation_participants cp
                            JOIN public.conversations c ON c.id = cp.conversation_id
                           WHERE cp.user_id = v_profile),
        'posts', (SELECT coalesce(jsonb_agg(jsonb_build_object(
                      'id', p.id, 'created_at', p.created_at, 'updated_at', p.updated_at,
                      'content', p.content, 'content_warning', p.content_warning,
                      'language', p.language, 'visibility', p.visibility,
                      'in_reply_to', p.in_reply_to, 'url', p.url, 'ap_id', p.ap_id,
                      'media_attachments', p.media_attachments,
                      'voice_attachments', p.voice_attachments, 'is_sensitive', p.is_sensitive,
                      'is_deleted', p.is_deleted, 'edit_history', p.edit_history,
                      'reblog', p.reblog, 'is_pinned', p.is_pinned) ORDER BY p.created_at), '[]'::jsonb)
                    FROM public.posts p WHERE p.author_id = v_profile),
        'post_interactions', (SELECT coalesce(jsonb_agg(jsonb_build_object(
                                  'post_id', i.post_id, 'type', i.interaction_type,
                                  'emoji_id', i.emoji_id, 'emoji', i.custom_emoji_content,
                                  'created_at', i.created_at) ORDER BY i.created_at), '[]'::jsonb)
                                FROM public.post_interactions i WHERE i.user_id = v_profile),
        'reactions', (SELECT coalesce(jsonb_agg(jsonb_build_object(
                          'message_id', r.message_id, 'emoji_id', r.emoji_id,
                          'emoji', r.custom_emoji_content, 'created_at', r.created_at)
                          ORDER BY r.created_at), '[]'::jsonb)
                        FROM public.reactions r WHERE r.user_id = v_profile),
        'following', (SELECT coalesce(jsonb_agg(public.profile_handle(f.following_id)
                          || jsonb_build_object('status', f.status, 'since', f.created_at)), '[]'::jsonb)
                        FROM public.follows f WHERE f.follower_id = v_profile),
        'followers', (SELECT coalesce(jsonb_agg(public.profile_handle(f.follower_id)
                          || jsonb_build_object('status', f.status, 'since', f.created_at)), '[]'::jsonb)
                        FROM public.follows f WHERE f.following_id = v_profile),
        'blocks', (SELECT coalesce(jsonb_agg(public.profile_handle(b.blocked_user_id)
                       || jsonb_build_object('since', b.created_at, 'reason', b.reason)), '[]'::jsonb)
                     FROM public.user_blocks b WHERE b.blocker_id = v_profile),
        'mutes', (SELECT coalesce(jsonb_agg(public.profile_handle(m.muted_user_id)
                      || jsonb_build_object('since', m.created_at, 'expires_at', m.expires_at)), '[]'::jsonb)
                    FROM public.user_mutes m WHERE m.muter_id = v_profile),
        'reports_filed', (SELECT coalesce(jsonb_agg(jsonb_build_object(
                              'id', r.id, 'created_at', r.created_at, 'type', r.report_type,
                              'reason', r.reason, 'comment', r.comment, 'status', r.status,
                              'reported_user_id', r.reported_user_id,
                              'reported_post_id', r.reported_post_id,
                              'reported_message_id', r.reported_message_id,
                              'reported_server_id', r.reported_server_id,
                              'resolved_at', r.resolved_at) ORDER BY r.created_at), '[]'::jsonb)
                            FROM public.reports r WHERE r.reporter_id = v_profile),
        'bots', (SELECT coalesce(jsonb_agg(jsonb_build_object(
                     'id', b.id, 'username', b.username, 'display_name', b.display_name,
                     'created_at', b.created_at, 'is_active', b.is_active)), '[]'::jsonb)
                   FROM public.bots b WHERE b.owner_id = v_profile),
        'media', v_media,
        'message_count', (SELECT count(*) FROM public.messages m
                           WHERE m.user_id = v_profile AND m.is_system IS NOT TRUE)
    );
    RETURN v_doc;
END;
$$;

-- The caller's own messages, oldest first, keyset-paged on (created_at, id). System
-- messages attributed to the caller (joins, calls) are not exported.
CREATE OR REPLACE FUNCTION public.export_my_messages(
    p_export_id uuid,
    p_after_created_at timestamptz DEFAULT NULL,
    p_after_id uuid DEFAULT NULL,
    p_limit integer DEFAULT 1000)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    v_profile uuid := public.get_current_profile_id();
    v_limit integer := least(greatest(coalesce(p_limit, 1000), 1), 2000);
    v_rows jsonb;
BEGIN
    IF v_profile IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.account_data_exports e
                    WHERE e.id = p_export_id AND e.profile_id = v_profile AND e.expires_at > now()) THEN
        RAISE SQLSTATE 'PT410' USING MESSAGE = 'export_expired',
            HINT = 'Request a new export.';
    END IF;

    WITH page AS (
        SELECT m.id, m.created_at, m.updated_at, m.channel_id, m.conversation_id, m.thread_id,
               m.reply_to, m.content, m.encrypted, m.is_deleted, m.is_pinned
          FROM public.messages m
         WHERE m.user_id = v_profile
           AND m.is_system IS NOT TRUE
           AND (p_after_created_at IS NULL
                OR (m.created_at, m.id) > (p_after_created_at, coalesce(p_after_id, '00000000-0000-0000-0000-000000000000'::uuid)))
         ORDER BY m.created_at, m.id
         LIMIT v_limit
    )
    SELECT coalesce(jsonb_agg(jsonb_build_object(
               'id', pg.id, 'created_at', pg.created_at, 'updated_at', pg.updated_at,
               'server_id', ch.server_id, 'server_name', sv.name,
               'channel_id', pg.channel_id, 'channel_name', ch.name,
               'conversation_id', pg.conversation_id, 'thread_id', pg.thread_id,
               'reply_to', pg.reply_to, 'content', pg.content, 'encrypted', pg.encrypted,
               'is_deleted', pg.is_deleted, 'is_pinned', pg.is_pinned)
               ORDER BY pg.created_at, pg.id), '[]'::jsonb)
      INTO v_rows
      FROM page pg
      LEFT JOIN public.channels ch ON ch.id = pg.channel_id
      LEFT JOIN public.servers sv ON sv.id = ch.server_id;

    IF jsonb_array_length(v_rows) < v_limit THEN
        RETURN jsonb_build_object('messages', v_rows, 'next', NULL);
    END IF;
    RETURN jsonb_build_object('messages', v_rows, 'next', jsonb_build_object(
        'created_at', v_rows -> -1 -> 'created_at', 'id', v_rows -> -1 -> 'id'));
END;
$$;

REVOKE ALL ON FUNCTION public.request_my_data_export() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.export_my_messages(uuid, timestamptz, uuid, integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.request_my_data_export() TO authenticated;
GRANT EXECUTE ON FUNCTION public.export_my_messages(uuid, timestamptz, uuid, integer) TO authenticated;

-- ---------------------------------------------------------------------------
-- Deletion
-- ---------------------------------------------------------------------------

-- Self-demotion is not escalation: lowering is_admin or is_moderator while leaving the
-- other moderation flags untouched passes, which account deletion needs for moderators.
CREATE OR REPLACE FUNCTION public.prevent_profile_moderation_self_update()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_role text;
    v_is_admin boolean;
BEGIN
    v_role := current_setting('request.jwt.claims', true)::jsonb ->> 'role';
    IF v_role = 'service_role' OR session_user = 'postgres' THEN
        RETURN NEW;
    END IF;

    IF NEW.is_suspended IS NOT DISTINCT FROM OLD.is_suspended
       AND NEW.is_silenced IS NOT DISTINCT FROM OLD.is_silenced
       AND NEW.force_sensitive IS NOT DISTINCT FROM OLD.force_sensitive
       AND (NEW.is_admin IS NOT DISTINCT FROM OLD.is_admin OR NEW.is_admin IS FALSE)
       AND (NEW.is_moderator IS NOT DISTINCT FROM OLD.is_moderator OR NEW.is_moderator IS FALSE)
    THEN
        RETURN NEW;
    END IF;

    SELECT EXISTS (
        SELECT 1 FROM public.profiles p
        WHERE p.auth_user_id = auth.uid()
          AND p.is_admin = true
          AND COALESCE(p.is_suspended, false) = false
    ) INTO v_is_admin;

    IF v_is_admin IS NOT TRUE THEN
        RAISE EXCEPTION
            'Permission denied: cannot modify moderation flags on profile'
            USING ERRCODE = '42501';
    END IF;

    RETURN NEW;
END;
$$;

-- deleted_at changes only while the same UPDATE detaches the auth user, which
-- profiles_update_own forbids a client from doing. SECURITY INVOKER: current_user is the
-- role issuing the UPDATE.
CREATE OR REPLACE FUNCTION public.protect_profile_deleted_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
AS $$
BEGIN
    IF NEW.deleted_at IS DISTINCT FROM OLD.deleted_at
       AND NEW.auth_user_id IS NOT NULL
       AND current_user IN ('anon', 'authenticated') THEN
        RAISE EXCEPTION 'deleted_at is set by account deletion only' USING ERRCODE = '42501';
    END IF;
    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.protect_profile_deleted_at() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS protect_profile_deleted_at_trigger ON public.profiles;
CREATE TRIGGER protect_profile_deleted_at_trigger
    BEFORE UPDATE OF deleted_at ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.protect_profile_deleted_at();

-- Profile federation stays silent for a tombstone; the Delete covers it.
CREATE OR REPLACE FUNCTION public.trigger_queue_profile_federation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF NEW.is_local != true OR NEW.deleted_at IS NOT NULL THEN
        RETURN NEW;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF (
            OLD.display_name IS NOT DISTINCT FROM NEW.display_name AND
            OLD.bio IS NOT DISTINCT FROM NEW.bio AND
            OLD.avatar_url IS NOT DISTINCT FROM NEW.avatar_url AND
            OLD.banner_url IS NOT DISTINCT FROM NEW.banner_url AND
            OLD.custom_status IS NOT DISTINCT FROM NEW.custom_status
        ) THEN
            RETURN NEW;
        END IF;
    END IF;

    PERFORM public.queue_federation_job(
        'federate-profile',
        jsonb_build_object(
            'type', CASE WHEN TG_OP = 'INSERT' THEN 'create' ELSE 'update' END,
            'profile_id', NEW.id,
            'username', NEW.username,
            'display_name', NEW.display_name,
            'bio', NEW.bio,
            'avatar_url', NEW.avatar_url,
            'banner_url', NEW.banner_url,
            'custom_status', NEW.custom_status
        ),
        3, 5, 3600
    );

    RETURN NEW;
END;
$$;

DROP FUNCTION IF EXISTS public.delete_my_account();

CREATE OR REPLACE FUNCTION public.delete_my_account(p_password text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    v_auth_id uuid := auth.uid();
    v_hash text;
    v_profile public.profiles%ROWTYPE;
    v_blocking text[];
    v_key text;
    v_actor text;
    v_inboxes text[];
BEGIN
    IF v_auth_id IS NULL THEN
        RAISE EXCEPTION 'Unauthorized: requires an authenticated session' USING ERRCODE = '42501';
    END IF;

    IF public.mfa_enabled_for(v_auth_id)
       AND (public.current_jwt_claims() ->> 'aal' IS DISTINCT FROM 'aal2'
            OR NOT public.session_step_up_fresh('totp', interval '10 minutes')) THEN
        RETURN jsonb_build_object('error', 'mfa_required');
    END IF;

    SELECT u.encrypted_password INTO v_hash FROM auth.users u WHERE u.id = v_auth_id;
    IF v_hash LIKE '$2%' THEN
        IF coalesce(p_password, '') = '' THEN
            RETURN jsonb_build_object('error', 'password_required');
        END IF;
        PERFORM public.assert_security_attempt_budget(v_auth_id, 'password');
        IF extensions.crypt(p_password, v_hash) IS DISTINCT FROM v_hash THEN
            PERFORM public.record_security_attempt(v_auth_id, 'password', false);
            RETURN jsonb_build_object('error', 'invalid_password');
        END IF;
    ELSIF NOT public.session_step_up_fresh(NULL, interval '10 minutes') THEN
        RETURN jsonb_build_object('error', 'reauthentication_required');
    END IF;

    SELECT p.* INTO v_profile FROM public.profiles p WHERE p.auth_user_id = v_auth_id;

    IF v_profile.id IS NOT NULL THEN
        SELECT array_agg(s.name ORDER BY s.name) INTO v_blocking
          FROM public.servers s
         WHERE s.owner = v_profile.id
           AND EXISTS (SELECT 1 FROM public.user_servers us
                        WHERE us.server_id = s.id AND us.user_id <> v_profile.id);
        IF v_blocking IS NOT NULL THEN
            RETURN jsonb_build_object('error', 'transfer_ownership_required',
                                      'servers', to_jsonb(v_blocking));
        END IF;

        -- Snapshot for the ActivityPub Delete before follows and keys are purged.
        IF v_profile.is_local IS NOT FALSE AND v_profile.username IS NOT NULL THEN
            SELECT k.private_key INTO v_key FROM public.user_private_keys k WHERE k.user_id = v_profile.id;
            v_actor := coalesce(nullif(v_profile.federated_id, ''),
                                'https://' || v_profile.domain || '/users/' || v_profile.username);
            SELECT coalesce(array_agg(DISTINCT x.inbox), '{}') INTO v_inboxes
              FROM (SELECT coalesce(nullif(rp.shared_inbox_url, ''), rp.inbox_url) AS inbox
                      FROM public.follows f
                      JOIN public.profiles rp
                        ON rp.id = CASE WHEN f.follower_id = v_profile.id
                                        THEN f.following_id ELSE f.follower_id END
                     WHERE (f.follower_id = v_profile.id OR f.following_id = v_profile.id)
                       AND rp.is_local IS FALSE) x
             WHERE x.inbox LIKE 'https://%' OR x.inbox LIKE 'http://%';
            INSERT INTO public.deleted_actors (profile_id, username, domain, actor_uri, private_key, inboxes)
            VALUES (v_profile.id, v_profile.username, v_profile.domain, v_actor, v_key, v_inboxes)
            ON CONFLICT (profile_id) DO NOTHING;
        END IF;

        DELETE FROM public.servers s WHERE s.owner = v_profile.id;

        DELETE FROM public.user_key_pairs        WHERE user_id = v_profile.id;
        DELETE FROM public.megolm_session_shares WHERE sender_user_id = v_profile.id OR recipient_user_id = v_profile.id;
        DELETE FROM public.megolm_key_requests   WHERE requester_user_id = v_profile.id OR sender_user_id = v_profile.id;
        DELETE FROM public.megolm_key_backups    WHERE user_id = v_profile.id;
        DELETE FROM public.recovery_key_metadata WHERE user_id = v_profile.id;
        DELETE FROM public.mfa_recovery_codes    WHERE user_id IN (v_profile.id, v_auth_id);
        DELETE FROM public.follows               WHERE follower_id = v_profile.id OR following_id = v_profile.id;
        DELETE FROM public.timeline_entries      WHERE user_id = v_profile.id;
        DELETE FROM public.unread_counts         WHERE user_id = v_profile.id;
        DELETE FROM public.post_interactions     WHERE user_id = v_profile.id;
        DELETE FROM public.invites               WHERE created_by = v_profile.id;
        DELETE FROM public.user_servers          WHERE user_id = v_profile.id;
        DELETE FROM public.user_private_keys     WHERE user_id = v_profile.id;
        DELETE FROM public.push_subscriptions    WHERE user_id = v_profile.id;
        DELETE FROM public.notifications         WHERE user_id = v_profile.id;
        DELETE FROM public.user_blocks           WHERE blocker_id = v_profile.id OR blocked_user_id = v_profile.id;
        DELETE FROM public.user_mutes            WHERE muter_id = v_profile.id OR muted_user_id = v_profile.id;
        DELETE FROM public.user_roles            WHERE user_id = v_profile.id;
        DELETE FROM public.thread_members        WHERE user_id = v_profile.id;
        DELETE FROM public.voice_channel_participants WHERE user_id = v_profile.id;
        DELETE FROM public.notification_preferences   WHERE user_id = v_profile.id;
        DELETE FROM public.notification_channels      WHERE user_id = v_profile.id;
        DELETE FROM public.server_folders        WHERE user_id = v_profile.id;
        DELETE FROM public.emoji_favorites       WHERE user_id = v_profile.id;
        DELETE FROM public.gif_favorites         WHERE user_id = v_profile.id;
        DELETE FROM public.user_list_members     WHERE account_id = v_profile.id;
        DELETE FROM public.user_lists            WHERE user_id = v_profile.id;
        DELETE FROM public.account_data_exports  WHERE profile_id = v_profile.id;
        DELETE FROM public.account_security_attempts WHERE auth_user_id = v_auth_id;

        -- Deployments differ on these.
        BEGIN
            DELETE FROM public.user_devices WHERE user_id = v_profile.id;
        EXCEPTION WHEN undefined_table OR undefined_column THEN NULL;
        END;
        BEGIN
            DELETE FROM public.user_sessions WHERE user_id = v_profile.id;
        EXCEPTION WHEN undefined_table OR undefined_column THEN NULL;
        END;
        BEGIN
            DELETE FROM public.announcement_reads WHERE user_id = v_profile.id;
        EXCEPTION WHEN undefined_table OR undefined_column THEN NULL;
        END;
        BEGIN
            DELETE FROM public.emoji_usage WHERE user_id = v_profile.id;
        EXCEPTION WHEN undefined_table OR undefined_column THEN NULL;
        END;
        BEGIN
            UPDATE public.bot_tokens t SET is_active = false
             WHERE t.bot_id IN (SELECT b.id FROM public.bots b WHERE b.owner_id = v_profile.id);
            UPDATE public.bots b SET is_active = false WHERE b.owner_id = v_profile.id;
        EXCEPTION WHEN undefined_table OR undefined_column THEN NULL;
        END;

        -- auth_user_id = NULL detaches the row before the auth delete, so the cascade
        -- cannot reach it. The generated username satisfies profiles_username_check.
        UPDATE public.profiles SET
            username = 'deleted_' || replace(substr(v_profile.id::text, 1, 13), '-', ''),
            display_name = 'Deleted User',
            avatar_url = '/default_avatar.webp',
            banner_url = NULL,
            bio = NULL,
            color = NULL,
            status = 0,
            custom_status = NULL,
            profile_fields = '[]'::jsonb,
            appearance_settings = NULL,
            public_key = NULL,
            federated_id = NULL,
            inbox_url = NULL,
            outbox_url = NULL,
            followers_url = NULL,
            following_url = NULL,
            featured_url = NULL,
            shared_inbox_url = NULL,
            federation_metadata = '{}'::jsonb,
            is_admin = false,
            is_moderator = false,
            federation_enabled = false,
            federation_discoverable = false,
            followers_count = 0,
            following_count = 0,
            auth_user_id = NULL,
            deleted_at = now(),
            updated_at = now()
        WHERE id = v_profile.id;

        PERFORM public.queue_federation_job('account-deleted',
            jsonb_build_object('profile_id', v_profile.id, 'auth_user_id', v_auth_id),
            3, 10, 86400);
    END IF;

    -- Cascades sessions, identities and factors through GoTrue's foreign keys.
    DELETE FROM auth.users WHERE id = v_auth_id;

    RETURN jsonb_build_object('success', true);
END;
$$;

REVOKE ALL ON FUNCTION public.delete_my_account(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.delete_my_account(text) TO authenticated;

-- ---------------------------------------------------------------------------
-- Ownership and privileges
-- ---------------------------------------------------------------------------

DO $$
DECLARE
    fn regprocedure;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'postgres') THEN
        RAISE NOTICE 'postgres role absent, ownership left with %', current_user;
        RETURN;
    END IF;
    FOR fn IN
        SELECT p.oid::regprocedure
          FROM pg_proc p
         WHERE p.pronamespace = 'public'::regnamespace
           AND p.proname IN (
               'current_jwt_claims', 'mfa_enabled_for', 'session_meets_aal',
               'session_step_up_fresh', 'enforce_request_assurance',
               'assert_security_attempt_budget', 'record_security_attempt',
               'record_security_notice', 'verify_my_password', 'normalize_recovery_code',
               'hash_recovery_code', 'recovery_code_owner', 'generate_mfa_recovery_codes',
               'get_mfa_recovery_status', 'save_recovery_codes', 'verify_recovery_code',
               'redeem_recovery_code_and_disable_mfa', 'list_my_sessions', 'revoke_my_session',
               'on_auth_session_created', 'on_auth_session_deleted',
               'on_auth_mfa_factor_changed', 'on_auth_password_changed', 'profile_handle',
               'request_my_data_export', 'export_my_messages',
               'prevent_profile_moderation_self_update', 'protect_profile_deleted_at',
               'trigger_queue_profile_federation', 'delete_my_account')
           AND pg_get_userbyid(p.proowner) <> 'postgres'
    LOOP
        EXECUTE format('ALTER FUNCTION %s OWNER TO postgres', fn);
        RAISE NOTICE '% now owned by postgres', fn;
    END LOOP;
END;
$$;

ALTER TABLE public.account_security_attempts OWNER TO postgres;
ALTER TABLE public.account_data_exports OWNER TO postgres;
ALTER TABLE public.deleted_actors OWNER TO postgres;

REVOKE ALL ON public.mfa_recovery_codes FROM PUBLIC, anon, authenticated, service_role;

-- Privileges the postgres-owned definers above exercise, per table. Production owns
-- several of these tables as supabase_admin with narrower grants than a fresh install.
DO $$
DECLARE
    r record;
    v_priv text;
    v_missing text[] := '{}';
BEGIN
    FOR r IN
        SELECT * FROM (VALUES
            ('auth.users',                         'SELECT,DELETE'),
            ('auth.sessions',                      'SELECT,DELETE'),
            ('auth.mfa_factors',                   'SELECT,DELETE'),
            ('public.profiles',                    'SELECT,UPDATE'),
            ('public.mfa_recovery_codes',          'SELECT,INSERT,UPDATE,DELETE'),
            ('public.notifications',               'SELECT,INSERT,DELETE'),
            ('public.push_subscriptions',          'SELECT,DELETE'),
            ('public.account_security_attempts',   'SELECT,INSERT,DELETE'),
            ('public.account_data_exports',        'SELECT,INSERT,DELETE'),
            ('public.deleted_actors',              'SELECT,INSERT'),
            ('public.notification_preferences',    'SELECT,DELETE'),
            ('public.notification_channels',       'SELECT,DELETE'),
            ('public.server_folders',              'SELECT,DELETE'),
            ('public.servers',                     'SELECT,DELETE'),
            ('public.user_servers',                'SELECT,DELETE'),
            ('public.conversations',               'SELECT'),
            ('public.conversation_participants',   'SELECT'),
            ('public.channels',                    'SELECT'),
            ('public.messages',                    'SELECT'),
            ('public.posts',                       'SELECT'),
            ('public.post_interactions',           'SELECT,DELETE'),
            ('public.reactions',                   'SELECT'),
            ('public.reports',                     'SELECT'),
            ('public.follows',                     'SELECT,DELETE'),
            ('public.user_blocks',                 'SELECT,DELETE'),
            ('public.user_mutes',                  'SELECT,DELETE'),
            ('public.user_key_pairs',              'SELECT,DELETE'),
            ('public.megolm_session_shares',       'SELECT,DELETE'),
            ('public.megolm_key_requests',         'SELECT,DELETE'),
            ('public.megolm_key_backups',          'SELECT,DELETE'),
            ('public.recovery_key_metadata',       'SELECT,DELETE'),
            ('public.timeline_entries',            'SELECT,DELETE'),
            ('public.unread_counts',               'SELECT,DELETE'),
            ('public.invites',                     'SELECT,DELETE'),
            ('public.user_private_keys',           'SELECT,DELETE'),
            ('public.user_roles',                  'SELECT,DELETE'),
            ('public.thread_members',              'SELECT,DELETE'),
            ('public.voice_channel_participants',  'SELECT,DELETE'),
            ('public.emoji_favorites',             'SELECT,DELETE'),
            ('public.gif_favorites',               'SELECT,DELETE'),
            ('public.user_list_members',           'SELECT,DELETE'),
            ('public.user_lists',                  'SELECT,DELETE'),
            ('public.user_devices',                'SELECT,DELETE'),
            ('public.user_sessions',               'SELECT,DELETE'),
            ('public.announcement_reads',          'SELECT,DELETE'),
            ('public.emoji_usage',                 'SELECT,DELETE'),
            ('public.bots',                        'SELECT,UPDATE'),
            ('public.bot_tokens',                  'SELECT,UPDATE')
        ) AS t(tbl, privs)
    LOOP
        IF to_regclass(r.tbl) IS NULL THEN
            CONTINUE;
        END IF;
        FOREACH v_priv IN ARRAY string_to_array(r.privs, ',') LOOP
            IF has_table_privilege('postgres', r.tbl, v_priv) THEN
                CONTINUE;
            END IF;
            BEGIN
                EXECUTE format('GRANT %s ON %s TO postgres', v_priv, r.tbl);
                RAISE NOTICE 'granted % on % to postgres', v_priv, r.tbl;
            EXCEPTION WHEN insufficient_privilege THEN
                NULL;
            END;
            IF NOT has_table_privilege('postgres', r.tbl, v_priv) THEN
                v_missing := v_missing || format('%s %s', v_priv, r.tbl);
            END IF;
        END LOOP;
    END LOOP;

    IF cardinality(v_missing) > 0 THEN
        RAISE EXCEPTION 'postgres lacks privileges the account-security functions use: %',
            array_to_string(v_missing, ', ')
            USING HINT = 'Apply this migration as supabase_admin.';
    END IF;
END;
$$;

COMMIT;

NOTIFY pgrst, 'reload config';
NOTIFY pgrst, 'reload schema';
