#!/usr/bin/env bash
# Ephemeral Postgres + GoTrue + PostgREST stack for E2E runs. No external
# secrets: credentials are generated here into e2e/stack.env.
#
#   e2e/stack.sh up      tear down, raise containers, build the schema from init/
#   e2e/stack.sh seed    create the fixture (users via GoTrue, graph via PostgREST)
#   e2e/stack.sh smoke   sign in and assert one RLS allow and one RLS deny
#   e2e/stack.sh verify  up + seed + smoke
#   e2e/stack.sh down    remove containers, volumes, network and stack.env
#   e2e/stack.sh status  what is running and on which port
#   e2e/stack.sh logs    compose logs
#
# A failed `up` leaves its containers for inspection; `down` clears them whatever
# state they reached, and `up` runs `down` first.
#
# The schema is built exactly as scripts/run-db-tests.sh builds it:
# scripts/test-db/supabase-compat.sql as supabase_admin, then init/init.sql as
# postgres. Two additions that script does not need: role passwords (nothing
# connects over TCP in the pgTAP run) and e2e/jwt-claims-compat.sql.
#
# Not covered: storage, realtime, imgproxy, postgres-meta, the federation
# backend and Redis. The gateway answers 501 on those paths.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
E2E="$ROOT/e2e"
PROJECT="hme2e"
COMPOSE_FILE="$E2E/docker-compose.yml"
ENV_FILE="$E2E/stack.env"
FIXTURE_FILE="$E2E/fixture.json"

PORT="${E2E_PORT:-54480}"
BASE_URL="http://localhost:$PORT"

# Throwaway values. The database publishes no port and the stack is destroyed
# by `down`, so these are configuration, not credentials.
DB_PASSWORD="e2e-local-postgres"
JWT_SECRET="e2e-local-jwt-secret-at-least-32-characters"

log()  { printf '\033[36m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[32mok \033[0m %s\n' "$*"; }
err()  { printf '\033[31mFAIL\033[0m %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

compose() {
  local args=(-p "$PROJECT" -f "$COMPOSE_FILE")
  [ -f "$ENV_FILE" ] && args+=(--env-file "$ENV_FILE")
  docker compose "${args[@]}" "$@"
}

# HS256 JWT. Mirrors sign_jwt in self-host/configure.sh.
sign_jwt() {
  local role="$1" secret="$2" now exp header payload body sig
  now=$(date +%s); exp=$((now + 86400))
  header=$(printf '{"alg":"HS256","typ":"JWT"}' | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
  payload=$(printf '{"role":"%s","iss":"supabase","iat":%d,"exp":%d}' "$role" "$now" "$exp" |
    openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
  body="${header}.${payload}"
  sig=$(printf '%s' "$body" | openssl dgst -sha256 -hmac "$secret" -binary |
    openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
  printf '%s.%s' "$body" "$sig"
}

write_env() {
  local anon service
  anon=$(sign_jwt anon "$JWT_SECRET")
  service=$(sign_jwt service_role "$JWT_SECRET")
  cat >"$ENV_FILE" <<EOF
# Generated by e2e/stack.sh. Recreated on every \`up\`; removed by \`down\`.
E2E_PORT=$PORT
E2E_DB_PASSWORD=$DB_PASSWORD
E2E_JWT_SECRET=$JWT_SECRET

# Consumed by e2e/seed.mjs and e2e/smoke.mjs.
E2E_SUPABASE_URL=$BASE_URL
E2E_SUPABASE_ANON_KEY=$anon
E2E_SUPABASE_SERVICE_ROLE_KEY=$service

# Names tests/e2e/helpers/e2e-helpers.ts and playwright.config.ts read.
TEST_SUPABASE_URL=$BASE_URL
TEST_SUPABASE_ANON_KEY=$anon
TEST_SUPABASE_SERVICE_ROLE_KEY=$service
VITE_SUPABASE_URL=$BASE_URL
VITE_SUPABASE_ANON_KEY=$anon
EOF
  ok "wrote e2e/stack.env"
}

db_cid() { compose ps -q db; }

psql_admin() { # superuser; owns the auth and realtime schemas
  docker exec -i "$(db_cid)" psql -U supabase_admin -h 127.0.0.1 -d postgres "$@"
}
psql_postgres() {
  docker exec -i "$(db_cid)" psql -U postgres -d postgres "$@"
}

wait_http() { # wait_http <url> <expected-status-regex> <what> [tries]
  local url="$1" want="$2" what="$3" tries="${4:-90}" code
  for _ in $(seq 1 "$tries"); do
    code=$(curl -s -o /dev/null -w '%{http_code}' "$url" || true)
    [[ "$code" =~ $want ]] && { ok "$what ($code)"; return 0; }
    sleep 1
  done
  err "$what never answered (last status ${code:-none})"
  return 1
}

cmd_up() {
  command -v docker >/dev/null || die "docker is required"
  command -v openssl >/dev/null || die "openssl is required"
  command -v curl >/dev/null || die "curl is required"

  # Always from empty. init.sql is not written to run twice over itself, and a
  # container left by an interrupted run would otherwise be reused.
  cmd_down

  write_env

  log "starting postgres"
  compose up -d db
  local cid; cid="$(db_cid)"
  # Five consecutive answers, as in scripts/run-db-tests.sh: the image restarts
  # the server partway through init and a single successful query is not the
  # server that stays up.
  local streak=0
  for _ in $(seq 1 120); do
    if docker exec "$cid" psql -U postgres -h 127.0.0.1 -d postgres -tAc 'select 1' >/dev/null 2>&1; then
      streak=$((streak + 1)); [ "$streak" -ge 5 ] && break
    else streak=0; fi
    sleep 1
  done
  [ "$streak" -ge 5 ] || { docker logs "$cid" | tail -20; die "postgres never stabilised"; }
  ok "postgres up"

  # GoTrue and PostgREST connect over TCP as roles the image leaves without a
  # password. Set them before either service starts.
  log "setting role passwords"
  psql_admin -q -v ON_ERROR_STOP=1 -v pw="$DB_PASSWORD" <<'SQL'
\set qpw '''' :pw ''''
ALTER ROLE authenticator WITH LOGIN PASSWORD :qpw;
ALTER ROLE supabase_auth_admin WITH LOGIN PASSWORD :qpw;
ALTER ROLE postgres WITH PASSWORD :qpw;
SQL

  log "starting auth, rest and gateway"
  compose up -d
  wait_http "$BASE_URL/health" '^200$' "gateway"
  # GoTrue answers /health only once its auth-schema migrations have finished.
  wait_http "$BASE_URL/auth/v1/health" '^200$' "gotrue"

  build_schema

  log "reloading PostgREST schema cache"
  psql_postgres -q -c "NOTIFY pgrst, 'reload schema'"
  # PostgREST answers 401 on the root without a key; that is a live service.
  wait_http "$BASE_URL/rest/v1/" '^(200|400|401)$' "postgrest"

  ok "stack up on $BASE_URL"
}

build_schema() {
  local cid; cid="$(db_cid)"

  log "building schema from init/"
  docker exec "$cid" rm -rf /db_schema
  docker cp "$ROOT/db_schema" "$cid:/db_schema" >/dev/null
  docker cp "$ROOT/scripts/test-db/supabase-compat.sql" "$cid:/compat.sql" >/dev/null
  docker cp "$E2E/jwt-claims-compat.sql" "$cid:/jwt-claims-compat.sql" >/dev/null

  # As in scripts/run-db-tests.sh: the realtime schema belongs to supabase_admin
  # and postgres is not superuser in this image.
  docker exec "$cid" psql -U supabase_admin -h 127.0.0.1 -d postgres -q -f /compat.sql 2>&1 |
    grep -v 'already exists, skipping' || true

  docker exec "$cid" psql -U postgres -d postgres -tAc \
    "SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='realtime' AND p.proname='send'" | grep -q 1 ||
    die "realtime.send stub missing after compat; broadcast triggers will fail"

  docker exec "$cid" psql -U supabase_admin -h 127.0.0.1 -d postgres -q \
    -v ON_ERROR_STOP=1 -f /jwt-claims-compat.sql

  # init.sql narrates every skipped policy and index at NOTICE level; warnings
  # and errors still come through.
  docker exec -w /db_schema/init -e PGOPTIONS='-c client_min_messages=warning' \
    "$cid" psql -U postgres -d postgres -q -f init.sql >/dev/null

  # A JWT-shaped claims GUC must reach auth.uid(). Asserted here because a null
  # uid makes every later RLS deny look deliberate.
  local uid
  uid=$(docker exec "$cid" psql -U postgres -d postgres -tAc \
    "SELECT set_config('request.jwt.claims','{\"sub\":\"aaaaaaaa-0000-0000-0000-000000000001\"}',false) IS NOT NULL
       AND auth.uid() = 'aaaaaaaa-0000-0000-0000-000000000001'::uuid")
  [ "$uid" = "t" ] || die "auth.uid() does not read request.jwt.claims"
  ok "schema built; auth.uid() reads request.jwt.claims"
}

require_env() {
  [ -f "$ENV_FILE" ] || die "e2e/stack.env missing - run: npm run e2e:up"
}

cmd_seed() {
  require_env
  log "seeding fixture"
  node "$E2E/seed.mjs"
}

cmd_smoke() {
  require_env
  [ -f "$FIXTURE_FILE" ] || die "e2e/fixture.json missing - run: npm run e2e:seed"
  node "$E2E/smoke.mjs"
}

cmd_down() {
  log "tearing down"
  # Ordinary path. Tolerates a half-created stack.
  compose down -v --remove-orphans --timeout 5 >/dev/null 2>&1 || true

  # Anything compose could not account for - a container from an interrupted
  # run, a compose file edited since bring-up - still carries the project label.
  local leftovers
  leftovers=$(docker ps -aq --filter "label=com.docker.compose.project=$PROJECT" || true)
  [ -n "$leftovers" ] && docker rm -f $leftovers >/dev/null 2>&1 || true
  leftovers=$(docker volume ls -q --filter "label=com.docker.compose.project=$PROJECT" || true)
  [ -n "$leftovers" ] && docker volume rm -f $leftovers >/dev/null 2>&1 || true
  leftovers=$(docker network ls -q --filter "label=com.docker.compose.project=$PROJECT" || true)
  [ -n "$leftovers" ] && docker network rm $leftovers >/dev/null 2>&1 || true

  rm -f "$ENV_FILE" "$FIXTURE_FILE"
  ok "stack down"
}

cmd_status() {
  printf 'project %s, url %s\n' "$PROJECT" "$BASE_URL"
  docker ps -a --filter "label=com.docker.compose.project=$PROJECT" \
    --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}'
  [ -f "$ENV_FILE" ] && printf 'stack.env present\n' || printf 'stack.env absent\n'
  [ -f "$FIXTURE_FILE" ] && printf 'fixture.json present\n' || printf 'fixture.json absent\n'
}

case "${1:-}" in
  up)     cmd_up ;;
  seed)   cmd_seed ;;
  smoke)  cmd_smoke ;;
  verify) cmd_up; cmd_seed; cmd_smoke ;;
  down)   cmd_down ;;
  status) cmd_status ;;
  logs)   shift; compose logs "$@" ;;
  *)      die "usage: stack.sh {up|seed|smoke|verify|down|status|logs}" ;;
esac
