#!/usr/bin/env bash
# Flattens db_schema/init/ into one migration, so the chain builds from zero. No migration
# creates public.servers or the other 102 tables init/ declares.
#
# Includes are expanded and \echo dropped: the CLI applies a migration as a string, where psql
# meta-commands do not resolve.
#
#   build-baseline-migration.sh <version>   write db_schema/migrations/<version>_baseline.sql
#   build-baseline-migration.sh --stdout    write to stdout
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INIT="$ROOT/db_schema/init"

[ -r "$INIT/init.sql" ] || { printf 'no %s\n' "$INIT/init.sql" >&2; exit 1; }

emit() {
  printf -- '-- Generated by scripts/build-baseline-migration.sh from db_schema/init/.\n'
  printf -- '-- Edit init/ and regenerate; edits here are lost.\n\n'
  # \i order is the dependency order: 03_tables_social.sql forward-references a table
  # 06_tables_misc.sql creates, so alphabetical is not equivalent.
  grep -oE '^\\i[[:space:]]+\S+' "$INIT/init.sql" | awk '{print $2}' | while read -r f; do
    [ -r "$INIT/$f" ] || { printf 'missing include: %s\n' "$f" >&2; exit 1; }
    printf -- '\n-- ==== %s ====\n' "$f"
    # psql meta-commands are lines beginning with a backslash.
    grep -vE '^\\' "$INIT/$f"
  done
}

if [ "${1:-}" = "--stdout" ]; then
  emit
  exit 0
fi

VERSION="${1:?usage: build-baseline-migration.sh <version>|--stdout}"
OUT="$ROOT/db_schema/migrations/${VERSION}_baseline.sql"
emit > "$OUT"
printf 'wrote %s (%s bytes)\n' "$OUT" "$(wc -c < "$OUT")"
