#!/usr/bin/env bash
# Ephemeral Postgres + PostgREST stack for the federation round-trip run, and
# the runner for e2e/federation/roundtrip.ts.
#
#   e2e/federation/stack.sh up      tear down, raise containers, build the schema from init/
#   e2e/federation/stack.sh test    run roundtrip.ts against the stack
#   e2e/federation/stack.sh verify  up + test
#   e2e/federation/stack.sh down    remove containers, volumes, network and stack.env
#   e2e/federation/stack.sh status  what is running and on which port
#   e2e/federation/stack.sh logs    compose logs
#
# Project name and port differ from e2e/stack.sh so both stacks can be up at
# once. A failed `up` leaves its containers for inspection; `down` clears them
# whatever state they reached, and `up` runs `down` first.
#
# The schema is built exactly as e2e/stack.sh builds it:
# scripts/test-db/supabase-compat.sql as supabase_admin, then init/init.sql as
# postgres, then e2e/jwt-claims-compat.sql so auth.uid() reads the PostgREST
# v13 claims GUC.
#
# `test` runs from a scratch directory: winston writes logs/ relative to the
# working directory, and config/index.ts loads .env from it - running in the
# repo would pick up a developer's real federation-backend/.env.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FED="$ROOT/e2e/federation"
PROJECT="hmfed"
COMPOSE_FILE="$FED/docker-compose.yml"
ENV_FILE="$FED/stack.env"

PORT="${HMFED_PORT:-54580}"
BASE_URL="http://localhost:$PORT"
SUBNET="${HMFED_SUBNET:-203.0.113.0/24}"

# Throwaway values. The database publishes no port and the stack is destroyed
# by `down`, so these are configuration, not credentials.
DB_PASSWORD="hmfed-local-postgres"
JWT_SECRET="hmfed-local-jwt-secret-at-least-32-characters"

log()  { printf '\033[36m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[32mok \033[0m %s\n' "$*"; }
err()  { printf '\033[31mFAIL\033[0m %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

compose() {
  local args=(-p "$PROJECT" -f "$COMPOSE_FILE")
  [ -f "$ENV_FILE" ] && args+=(--env-file "$ENV_FILE")
  docker compose "${args[@]}" "$@"
}

# HS256 JWT. Mirrors sign_jwt in self-host/configure.sh.
sign_jwt() {
  local role="$1" secret="$2" now exp header payload body sig
  now=$(date +%s); exp=$((now + 86400))
  header=$(printf '{"alg":"HS256","typ":"JWT"}' | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
  payload=$(printf '{"role":"%s","iss":"supabase","iat":%d,"exp":%d}' "$role" "$now" "$exp" |
    openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
  body="${header}.${payload}"
  sig=$(printf '%s' "$body" | openssl dgst -sha256 -hmac "$secret" -binary |
    openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
  printf '%s.%s' "$body" "$sig"
}

# Bridge gateway of the compose network: an address on the host that is not
# loopback and not RFC 1918, so federation code will fetch it.
peer_host() { printf '%s' "${SUBNET%.*/*}.1"; }

write_env() {
  local anon service
  anon=$(sign_jwt anon "$JWT_SECRET")
  service=$(sign_jwt service_role "$JWT_SECRET")
  cat >"$ENV_FILE" <<EOF
# Generated by e2e/federation/stack.sh. Recreated on every \`up\`; removed by \`down\`.
HMFED_PORT=$PORT
HMFED_SUBNET=$SUBNET
HMFED_DB_PASSWORD=$DB_PASSWORD
HMFED_JWT_SECRET=$JWT_SECRET

# Consumed by e2e/federation/roundtrip.ts.
HMFED_SUPABASE_URL=$BASE_URL
HMFED_SUPABASE_ANON_KEY=$anon
HMFED_SUPABASE_SERVICE_ROLE_KEY=$service
HMFED_PEER_HOST=$(peer_host)
EOF
  ok "wrote e2e/federation/stack.env"
}

db_cid() { compose ps -q db; }

psql_admin() { # superuser; owns the auth and realtime schemas
  docker exec -i "$(db_cid)" psql -U supabase_admin -h 127.0.0.1 -d postgres "$@"
}
psql_postgres() {
  docker exec -i "$(db_cid)" psql -U postgres -d postgres "$@"
}

wait_http() { # wait_http <url> <expected-status-regex> <what> [tries]
  local url="$1" want="$2" what="$3" tries="${4:-90}" code
  for _ in $(seq 1 "$tries"); do
    code=$(curl -s -o /dev/null -w '%{http_code}' "$url" || true)
    [[ "$code" =~ $want ]] && { ok "$what ($code)"; return 0; }
    sleep 1
  done
  err "$what never answered (last status ${code:-none})"
  return 1
}

cmd_up() {
  command -v docker >/dev/null || die "docker is required"
  command -v openssl >/dev/null || die "openssl is required"
  command -v curl >/dev/null || die "curl is required"

  # Always from empty. init.sql is not written to run twice over itself, and a
  # container left by an interrupted run would otherwise be reused.
  cmd_down

  write_env

  log "starting postgres"
  compose up -d db
  local cid; cid="$(db_cid)"
  # Five consecutive answers, as in scripts/run-db-tests.sh: the image restarts
  # the server partway through init and a single successful query is not the
  # server that stays up.
  local streak=0
  for _ in $(seq 1 120); do
    if docker exec "$cid" psql -U postgres -h 127.0.0.1 -d postgres -tAc 'select 1' >/dev/null 2>&1; then
      streak=$((streak + 1)); [ "$streak" -ge 5 ] && break
    else streak=0; fi
    sleep 1
  done
  [ "$streak" -ge 5 ] || { docker logs "$cid" | tail -20; die "postgres never stabilised"; }
  ok "postgres up"

  # PostgREST connects over TCP as a role the image leaves without a password.
  log "setting role passwords"
  psql_admin -q -v ON_ERROR_STOP=1 -v pw="$DB_PASSWORD" <<'SQL'
\set qpw '''' :pw ''''
ALTER ROLE authenticator WITH LOGIN PASSWORD :qpw;
ALTER ROLE postgres WITH PASSWORD :qpw;
SQL

  log "starting rest and gateway"
  compose up -d
  wait_http "$BASE_URL/health" '^200$' "gateway"

  build_schema

  log "reloading PostgREST schema cache"
  psql_postgres -q -c "NOTIFY pgrst, 'reload schema'"
  # PostgREST answers 401 on the root without a key; that is a live service.
  wait_http "$BASE_URL/rest/v1/" '^(200|400|401)$' "postgrest"

  # The peer inbox in roundtrip.ts is only reachable through this address.
  ip -4 addr show 2>/dev/null | grep -q " $(peer_host)/" ||
    die "compose network gateway $(peer_host) is not on a host interface"
  ok "peer address $(peer_host) is up"

  ok "stack up on $BASE_URL"
}

build_schema() {
  local cid; cid="$(db_cid)"

  log "building schema from init/"
  docker exec "$cid" rm -rf /db_schema
  docker cp "$ROOT/db_schema" "$cid:/db_schema" >/dev/null
  docker cp "$ROOT/scripts/test-db/supabase-compat.sql" "$cid:/compat.sql" >/dev/null
  docker cp "$ROOT/e2e/jwt-claims-compat.sql" "$cid:/jwt-claims-compat.sql" >/dev/null

  # The realtime schema belongs to supabase_admin and postgres is not
  # superuser in this image.
  docker exec "$cid" psql -U supabase_admin -h 127.0.0.1 -d postgres -q -f /compat.sql 2>&1 |
    grep -v 'already exists, skipping' || true

  docker exec "$cid" psql -U postgres -d postgres -tAc \
    "SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='realtime' AND p.proname='send'" | grep -q 1 ||
    die "realtime.send stub missing after compat; broadcast triggers will fail"

  docker exec "$cid" psql -U supabase_admin -h 127.0.0.1 -d postgres -q \
    -v ON_ERROR_STOP=1 -f /jwt-claims-compat.sql

  # init.sql narrates every skipped policy and index at NOTICE level; warnings
  # and errors still come through.
  PGOPTIONS='-c client_min_messages=warning' \
    "$ROOT/scripts/test-db/load-schema.sh" "$cid"

  # The inbox stores every activity through this RPC; without it every case
  # fails at the same place for a reason unrelated to what it covers.
  docker exec "$cid" psql -U postgres -d postgres -tAc \
    "SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.proname='upsert_ap_activity'" | grep -q 1 ||
    die "upsert_ap_activity missing after init.sql"
  ok "schema built"
}

cmd_test() {
  [ -f "$ENV_FILE" ] || die "e2e/federation/stack.env missing - run: e2e/federation/stack.sh up"
  local tsx="$ROOT/federation-backend/node_modules/.bin/tsx"
  [ -x "$tsx" ] || die "$tsx missing - run npm install in federation-backend/"

  local rundir status=0
  rundir="$(mktemp -d)"
  ( cd "$rundir" && "$tsx" "$FED/roundtrip.ts" ) || status=$?
  rm -rf "$rundir"
  return $status
}

cmd_down() {
  log "tearing down"
  compose down -v --remove-orphans --timeout 5 >/dev/null 2>&1 || true

  # Anything compose could not account for - a container from an interrupted
  # run, a compose file edited since bring-up - still carries the project label.
  local leftovers
  leftovers=$(docker ps -aq --filter "label=com.docker.compose.project=$PROJECT" || true)
  [ -n "$leftovers" ] && docker rm -f $leftovers >/dev/null 2>&1 || true
  leftovers=$(docker volume ls -q --filter "label=com.docker.compose.project=$PROJECT" || true)
  [ -n "$leftovers" ] && docker volume rm -f $leftovers >/dev/null 2>&1 || true
  leftovers=$(docker network ls -q --filter "label=com.docker.compose.project=$PROJECT" || true)
  [ -n "$leftovers" ] && docker network rm $leftovers >/dev/null 2>&1 || true

  rm -f "$ENV_FILE"
  ok "stack down"
}

cmd_status() {
  printf 'project %s, url %s, peer %s\n' "$PROJECT" "$BASE_URL" "$(peer_host)"
  docker ps -a --filter "label=com.docker.compose.project=$PROJECT" \
    --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}'
  [ -f "$ENV_FILE" ] && printf 'stack.env present\n' || printf 'stack.env absent\n'
}

case "${1:-}" in
  up)     cmd_up ;;
  test)   cmd_test ;;
  verify) cmd_up; cmd_test ;;
  down)   cmd_down ;;
  status) cmd_status ;;
  logs)   shift; compose logs "$@" ;;
  *)      die "usage: stack.sh {up|test|verify|down|status|logs}" ;;
esac
